//
// Generated by Bluespec Compiler, version 2024.07 (build b4f31db)
//
// On Fri Mar 13 11:37:58 CET 2026
//
//
// Ports:
// Name                         I/O  size props
// wrap128_toMem                  O   129
// wrap128_toMem_cap              I   161
//
// Combinational paths from inputs to outputs:
//   wrap128_toMem_cap -> wrap128_toMem
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_wrap128_toMem(wrap128_toMem_cap,
			    wrap128_toMem);
  // value method wrap128_toMem
  input  [160 : 0] wrap128_toMem_cap;
  output [128 : 0] wrap128_toMem;

  // signals for module outputs
  wire [128 : 0] wrap128_toMem;

  // remaining internal signals
  wire [127 : 0] x__h430;
  wire [25 : 0] IF_wrap128_toMem_cap_BIT_44_THEN_wrap128_toMem_ETC___d16;

  // value method wrap128_toMem
  assign wrap128_toMem = { wrap128_toMem_cap[160], x__h430 } ;

  // remaining internal signals
  assign IF_wrap128_toMem_cap_BIT_44_THEN_wrap128_toMem_ETC___d16 =
	     wrap128_toMem_cap[44] ?
	       { wrap128_toMem_cap[35:27],
		 wrap128_toMem_cap[43:41],
		 wrap128_toMem_cap[23:13],
		 wrap128_toMem_cap[40:38] } :
	       wrap128_toMem_cap[35:10] ;
  assign x__h430 =
	     { wrap128_toMem_cap[81:66],
	       wrap128_toMem_cap[64:63],
	       wrap128_toMem_cap[65],
	       ~wrap128_toMem_cap[62:44],
	       IF_wrap128_toMem_cap_BIT_44_THEN_wrap128_toMem_ETC___d16[25:17],
	       ~IF_wrap128_toMem_cap_BIT_44_THEN_wrap128_toMem_ETC___d16[16:15],
	       IF_wrap128_toMem_cap_BIT_44_THEN_wrap128_toMem_ETC___d16[14:3],
	       ~IF_wrap128_toMem_cap_BIT_44_THEN_wrap128_toMem_ETC___d16[2],
	       IF_wrap128_toMem_cap_BIT_44_THEN_wrap128_toMem_ETC___d16[1:0],
	       wrap128_toMem_cap[159:96] } ;
endmodule  // module_wrap128_toMem

