//
// Generated by Bluespec Compiler, version 2024.07 (build b4f31db)
//
// On Fri Mar 13 11:37:58 CET 2026
//
//
// Ports:
// Name                         I/O  size props
// wrap128_almightyCap            O   161 const
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_wrap128_almightyCap(wrap128_almightyCap);
  // value method wrap128_almightyCap
  output [160 : 0] wrap128_almightyCap;

  // signals for module outputs
  wire [160 : 0] wrap128_almightyCap;

  // value method wrap128_almightyCap
  assign wrap128_almightyCap =
	     161'h100000000000000000003FFFC7FFFFD10000003F0 ;
endmodule  // module_wrap128_almightyCap

