//
// Generated by Bluespec Compiler, version 2024.07 (build b4f31db)
//
// On Fri Mar 13 11:37:57 CET 2026
//
//
// Ports:
// Name                         I/O  size props
// wrap128_getSoftPerms           O    16
// wrap128_getSoftPerms_cap       I   161
//
// Combinational paths from inputs to outputs:
//   wrap128_getSoftPerms_cap -> wrap128_getSoftPerms
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_wrap128_getSoftPerms(wrap128_getSoftPerms_cap,
				   wrap128_getSoftPerms);
  // value method wrap128_getSoftPerms
  input  [160 : 0] wrap128_getSoftPerms_cap;
  output [15 : 0] wrap128_getSoftPerms;

  // signals for module outputs
  wire [15 : 0] wrap128_getSoftPerms;

  // value method wrap128_getSoftPerms
  assign wrap128_getSoftPerms = { 12'd0, wrap128_getSoftPerms_cap[81:78] } ;
endmodule  // module_wrap128_getSoftPerms

