//
// Generated by Bluespec Compiler, version 2024.07 (build b4f31db)
//
// On Fri Mar 13 11:37:57 CET 2026
//
//
// Ports:
// Name                         I/O  size props
// wrap128_setFlags               O   161
// wrap128_setFlags_cap           I   161
// wrap128_setFlags_flags         I     1
//
// Combinational paths from inputs to outputs:
//   (wrap128_setFlags_cap, wrap128_setFlags_flags) -> wrap128_setFlags
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_wrap128_setFlags(wrap128_setFlags_cap,
			       wrap128_setFlags_flags,
			       wrap128_setFlags);
  // value method wrap128_setFlags
  input  [160 : 0] wrap128_setFlags_cap;
  input  wrap128_setFlags_flags;
  output [160 : 0] wrap128_setFlags;

  // signals for module outputs
  wire [160 : 0] wrap128_setFlags;

  // value method wrap128_setFlags
  assign wrap128_setFlags =
	     { wrap128_setFlags_cap[160:66],
	       wrap128_setFlags_flags,
	       wrap128_setFlags_cap[64:0] } ;
endmodule  // module_wrap128_setFlags

