//
// Generated by Bluespec Compiler, version 2024.07 (build b4f31db)
//
// On Fri Mar 13 11:37:57 CET 2026
//
//
// Ports:
// Name                         I/O  size props
// wrap128_getKind                O    21
// wrap128_getKind_cap            I   161
//
// Combinational paths from inputs to outputs:
//   wrap128_getKind_cap -> wrap128_getKind
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_wrap128_getKind(wrap128_getKind_cap,
			      wrap128_getKind);
  // value method wrap128_getKind
  input  [160 : 0] wrap128_getKind_cap;
  output [20 : 0] wrap128_getKind;

  // signals for module outputs
  wire [20 : 0] wrap128_getKind;

  // remaining internal signals
  reg [2 : 0] CASE_wrap128_getKind_cap_BITS_62_TO_45_262140__ETC__q1;

  // value method wrap128_getKind
  assign wrap128_getKind =
	     { CASE_wrap128_getKind_cap_BITS_62_TO_45_262140__ETC__q1,
	       wrap128_getKind_cap[62:45] } ;

  // remaining internal signals
  always@(wrap128_getKind_cap)
  begin
    case (wrap128_getKind_cap[62:45])
      18'd262140:
	  CASE_wrap128_getKind_cap_BITS_62_TO_45_262140__ETC__q1 = 3'd3;
      18'd262141:
	  CASE_wrap128_getKind_cap_BITS_62_TO_45_262140__ETC__q1 = 3'd2;
      18'd262142:
	  CASE_wrap128_getKind_cap_BITS_62_TO_45_262140__ETC__q1 = 3'd1;
      18'd262143:
	  CASE_wrap128_getKind_cap_BITS_62_TO_45_262140__ETC__q1 = 3'd0;
      default: CASE_wrap128_getKind_cap_BITS_62_TO_45_262140__ETC__q1 = 3'd4;
    endcase
  end
endmodule  // module_wrap128_getKind

