//
// Generated by Bluespec Compiler, version 2024.07 (build b4f31db)
//
// On Fri Mar 13 11:37:57 CET 2026
//
//
// Ports:
// Name                         I/O  size props
// wrap128_setValidCap            O   161
// wrap128_setValidCap_cap        I   161
// wrap128_setValidCap_valid      I     1
//
// Combinational paths from inputs to outputs:
//   (wrap128_setValidCap_cap, wrap128_setValidCap_valid) -> wrap128_setValidCap
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_wrap128_setValidCap(wrap128_setValidCap_cap,
				  wrap128_setValidCap_valid,
				  wrap128_setValidCap);
  // value method wrap128_setValidCap
  input  [160 : 0] wrap128_setValidCap_cap;
  input  wrap128_setValidCap_valid;
  output [160 : 0] wrap128_setValidCap;

  // signals for module outputs
  wire [160 : 0] wrap128_setValidCap;

  // value method wrap128_setValidCap
  assign wrap128_setValidCap =
	     { wrap128_setValidCap_valid, wrap128_setValidCap_cap[159:0] } ;
endmodule  // module_wrap128_setValidCap

