//
// Generated by Bluespec Compiler, version 2024.07 (build b4f31db)
//
// On Fri Mar 13 11:37:57 CET 2026
//
//
// Ports:
// Name                         I/O  size props
// wrap128_isValidCap             O     1
// wrap128_isValidCap_cap         I   161
//
// Combinational paths from inputs to outputs:
//   wrap128_isValidCap_cap -> wrap128_isValidCap
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_wrap128_isValidCap(wrap128_isValidCap_cap,
				 wrap128_isValidCap);
  // value method wrap128_isValidCap
  input  [160 : 0] wrap128_isValidCap_cap;
  output wrap128_isValidCap;

  // signals for module outputs
  wire wrap128_isValidCap;

  // value method wrap128_isValidCap
  assign wrap128_isValidCap = wrap128_isValidCap_cap[160] ;
endmodule  // module_wrap128_isValidCap

