//
// Generated by Bluespec Compiler, version 2024.07 (build b4f31db)
//
// On Fri Mar 13 11:37:57 CET 2026
//
//
// Ports:
// Name                         I/O  size props
// wrap128_incOffset              O   162
// wrap128_incOffset_cap          I   161
// wrap128_incOffset_inc          I    64
//
// Combinational paths from inputs to outputs:
//   (wrap128_incOffset_cap, wrap128_incOffset_inc) -> wrap128_incOffset
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_wrap128_incOffset(wrap128_incOffset_cap,
				wrap128_incOffset_inc,
				wrap128_incOffset);
  // value method wrap128_incOffset
  input  [160 : 0] wrap128_incOffset_cap;
  input  [63 : 0] wrap128_incOffset_inc;
  output [161 : 0] wrap128_incOffset;

  // signals for module outputs
  wire [161 : 0] wrap128_incOffset;

  // remaining internal signals
  wire [63 : 0] result_d_address__h786, x__h701, x__h807;
  wire [49 : 0] highBitsfilter__h72,
		highOffsetBits__h73,
		signBits__h70,
		x__h100;
  wire [13 : 0] repBoundBits__h79, toBoundsM1__h83, toBounds__h82;
  wire [3 : 0] IF_wrap128_incOffset_cap_BITS_37_TO_35_9_ULT_w_ETC___d53;
  wire [2 : 0] repBound__h947;
  wire IF_wrap128_incOffset_inc_BIT_63_THEN_NOT_wrap1_ETC___d23,
       wrap128_incOffset_cap_BITS_159_TO_96_0_PLUS_wr_ETC___d43,
       wrap128_incOffset_cap_BITS_23_TO_21_7_ULT_wrap_ETC___d41,
       wrap128_incOffset_cap_BITS_37_TO_35_9_ULT_wrap_ETC___d40;

  // value method wrap128_incOffset
  assign wrap128_incOffset =
	     { highOffsetBits__h73 == 50'd0 &&
	       IF_wrap128_incOffset_inc_BIT_63_THEN_NOT_wrap1_ETC___d23 ||
	       wrap128_incOffset_cap[43:38] >= 6'd50,
	       (highOffsetBits__h73 == 50'd0 &&
		IF_wrap128_incOffset_inc_BIT_63_THEN_NOT_wrap1_ETC___d23 ||
		wrap128_incOffset_cap[43:38] >= 6'd50) &&
	       wrap128_incOffset_cap[160],
	       result_d_address__h786,
	       x__h807[13:0],
	       wrap128_incOffset_cap[81:10],
	       repBound__h947,
	       wrap128_incOffset_cap_BITS_37_TO_35_9_ULT_wrap_ETC___d40,
	       wrap128_incOffset_cap_BITS_23_TO_21_7_ULT_wrap_ETC___d41,
	       wrap128_incOffset_cap_BITS_159_TO_96_0_PLUS_wr_ETC___d43,
	       IF_wrap128_incOffset_cap_BITS_37_TO_35_9_ULT_w_ETC___d53 } ;

  // remaining internal signals
  assign IF_wrap128_incOffset_cap_BITS_37_TO_35_9_ULT_w_ETC___d53 =
	     { (wrap128_incOffset_cap_BITS_37_TO_35_9_ULT_wrap_ETC___d40 ==
		wrap128_incOffset_cap_BITS_159_TO_96_0_PLUS_wr_ETC___d43) ?
		 2'd0 :
		 ((wrap128_incOffset_cap_BITS_37_TO_35_9_ULT_wrap_ETC___d40 &&
		   !wrap128_incOffset_cap_BITS_159_TO_96_0_PLUS_wr_ETC___d43) ?
		    2'd1 :
		    2'd3),
	       (wrap128_incOffset_cap_BITS_23_TO_21_7_ULT_wrap_ETC___d41 ==
		wrap128_incOffset_cap_BITS_159_TO_96_0_PLUS_wr_ETC___d43) ?
		 2'd0 :
		 ((wrap128_incOffset_cap_BITS_23_TO_21_7_ULT_wrap_ETC___d41 &&
		   !wrap128_incOffset_cap_BITS_159_TO_96_0_PLUS_wr_ETC___d43) ?
		    2'd1 :
		    2'd3) } ;
  assign IF_wrap128_incOffset_inc_BIT_63_THEN_NOT_wrap1_ETC___d23 =
	     wrap128_incOffset_inc[63] ?
	       x__h701[13:0] >= toBounds__h82 &&
	       repBoundBits__h79 != wrap128_incOffset_cap[95:82] :
	       x__h701[13:0] < toBoundsM1__h83 ;
  assign highBitsfilter__h72 =
	     50'h3FFFFFFFFFFFF << wrap128_incOffset_cap[43:38] ;
  assign highOffsetBits__h73 = x__h100 & highBitsfilter__h72 ;
  assign repBoundBits__h79 = { wrap128_incOffset_cap[9:7], 11'd0 } ;
  assign repBound__h947 = wrap128_incOffset_cap[23:21] - 3'b001 ;
  assign result_d_address__h786 =
	     wrap128_incOffset_cap[159:96] + wrap128_incOffset_inc ;
  assign signBits__h70 = {50{wrap128_incOffset_inc[63]}} ;
  assign toBoundsM1__h83 = repBoundBits__h79 + ~wrap128_incOffset_cap[95:82] ;
  assign toBounds__h82 = repBoundBits__h79 - wrap128_incOffset_cap[95:82] ;
  assign wrap128_incOffset_cap_BITS_159_TO_96_0_PLUS_wr_ETC___d43 =
	     x__h807[13:11] < repBound__h947 ;
  assign wrap128_incOffset_cap_BITS_23_TO_21_7_ULT_wrap_ETC___d41 =
	     wrap128_incOffset_cap[23:21] < repBound__h947 ;
  assign wrap128_incOffset_cap_BITS_37_TO_35_9_ULT_wrap_ETC___d40 =
	     wrap128_incOffset_cap[37:35] < repBound__h947 ;
  assign x__h100 = wrap128_incOffset_inc[63:14] ^ signBits__h70 ;
  assign x__h701 = wrap128_incOffset_inc >> wrap128_incOffset_cap[43:38] ;
  assign x__h807 = result_d_address__h786 >> wrap128_incOffset_cap[43:38] ;
endmodule  // module_wrap128_incOffset

