//
// Generated by Bluespec Compiler, version 2024.07 (build b4f31db)
//
// On Fri Mar 13 11:37:58 CET 2026
//
//
// Ports:
// Name                         I/O  size props
// wrap128_validAsType            O     1
// wrap128_validAsType_dummy      I   161 unused
// wrap128_validAsType_checkType  I    64
//
// Combinational paths from inputs to outputs:
//   wrap128_validAsType_checkType -> wrap128_validAsType
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_wrap128_validAsType(wrap128_validAsType_dummy,
				  wrap128_validAsType_checkType,
				  wrap128_validAsType);
  // value method wrap128_validAsType
  input  [160 : 0] wrap128_validAsType_dummy;
  input  [63 : 0] wrap128_validAsType_checkType;
  output wrap128_validAsType;

  // signals for module outputs
  wire wrap128_validAsType;

  // value method wrap128_validAsType
  assign wrap128_validAsType = wrap128_validAsType_checkType <= 64'd262139 ;
endmodule  // module_wrap128_validAsType

