//
// Generated by Bluespec Compiler, version 2024.07 (build b4f31db)
//
// On Fri Mar 13 11:37:57 CET 2026
//
//
// Ports:
// Name                         I/O  size props
// wrap128_isInBounds             O     1
// wrap128_isInBounds_cap         I   161
// wrap128_isInBounds_isTopIncluded  I     1
//
// Combinational paths from inputs to outputs:
//   (wrap128_isInBounds_cap,
//    wrap128_isInBounds_isTopIncluded) -> wrap128_isInBounds
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_wrap128_isInBounds(wrap128_isInBounds_cap,
				 wrap128_isInBounds_isTopIncluded,
				 wrap128_isInBounds);
  // value method wrap128_isInBounds
  input  [160 : 0] wrap128_isInBounds_cap;
  input  wrap128_isInBounds_isTopIncluded;
  output wrap128_isInBounds;

  // signals for module outputs
  wire wrap128_isInBounds;

  // value method wrap128_isInBounds
  assign wrap128_isInBounds =
	     ((wrap128_isInBounds_cap[6] == wrap128_isInBounds_cap[4]) ?
		(wrap128_isInBounds_isTopIncluded ?
		   wrap128_isInBounds_cap[95:82] <=
		   wrap128_isInBounds_cap[37:24] :
		   wrap128_isInBounds_cap[95:82] <
		   wrap128_isInBounds_cap[37:24]) :
		wrap128_isInBounds_cap[6]) &&
	     ((wrap128_isInBounds_cap[5] == wrap128_isInBounds_cap[4]) ?
		wrap128_isInBounds_cap[95:82] >=
		wrap128_isInBounds_cap[23:10] :
		wrap128_isInBounds_cap[4]) ;
endmodule  // module_wrap128_isInBounds

