//
// Generated by Bluespec Compiler, version 2024.07 (build b4f31db)
//
// On Fri Mar 13 11:37:57 CET 2026
//
//
// Ports:
// Name                         I/O  size props
// wrap128_setOffset              O   162
// wrap128_setOffset_cap          I   161
// wrap128_setOffset_offset       I    64
//
// Combinational paths from inputs to outputs:
//   (wrap128_setOffset_cap, wrap128_setOffset_offset) -> wrap128_setOffset
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_wrap128_setOffset(wrap128_setOffset_cap,
				wrap128_setOffset_offset,
				wrap128_setOffset);
  // value method wrap128_setOffset
  input  [160 : 0] wrap128_setOffset_cap;
  input  [63 : 0] wrap128_setOffset_offset;
  output [161 : 0] wrap128_setOffset;

  // signals for module outputs
  wire [161 : 0] wrap128_setOffset;

  // remaining internal signals
  reg [1 : 0] mask__h773;
  wire [63 : 0] addBase__h804, result_d_address__h784, x__h701;
  wire [49 : 0] highOffsetBits__h73, mask__h805, signBits__h70, x__h100;
  wire [15 : 0] x__h855;
  wire [13 : 0] newAddrBits__h772,
		result_d_addrBits__h785,
		toBoundsM1__h83,
		toBounds__h82;
  wire [3 : 0] IF_wrap128_setOffset_cap_BITS_37_TO_35_8_ULT_w_ETC___d62;
  wire [2 : 0] repBound__h1035;
  wire IF_wrap128_setOffset_cap_BITS_43_TO_38_EQ_52_6_ETC___d52,
       IF_wrap128_setOffset_offset_BIT_63_THEN_NOT_wr_ETC___d19,
       wrap128_setOffset_cap_BITS_23_TO_21_6_ULT_wrap_ETC___d50,
       wrap128_setOffset_cap_BITS_37_TO_35_8_ULT_wrap_ETC___d49;

  // value method wrap128_setOffset
  assign wrap128_setOffset =
	     { highOffsetBits__h73 == 50'd0 &&
	       IF_wrap128_setOffset_offset_BIT_63_THEN_NOT_wr_ETC___d19 ||
	       wrap128_setOffset_cap[43:38] >= 6'd50,
	       (highOffsetBits__h73 == 50'd0 &&
		IF_wrap128_setOffset_offset_BIT_63_THEN_NOT_wr_ETC___d19 ||
		wrap128_setOffset_cap[43:38] >= 6'd50) &&
	       wrap128_setOffset_cap[160],
	       result_d_address__h784,
	       result_d_addrBits__h785,
	       wrap128_setOffset_cap[81:10],
	       repBound__h1035,
	       wrap128_setOffset_cap_BITS_37_TO_35_8_ULT_wrap_ETC___d49,
	       wrap128_setOffset_cap_BITS_23_TO_21_6_ULT_wrap_ETC___d50,
	       IF_wrap128_setOffset_cap_BITS_43_TO_38_EQ_52_6_ETC___d52,
	       IF_wrap128_setOffset_cap_BITS_37_TO_35_8_ULT_w_ETC___d62 } ;

  // remaining internal signals
  assign IF_wrap128_setOffset_cap_BITS_37_TO_35_8_ULT_w_ETC___d62 =
	     { (wrap128_setOffset_cap_BITS_37_TO_35_8_ULT_wrap_ETC___d49 ==
		IF_wrap128_setOffset_cap_BITS_43_TO_38_EQ_52_6_ETC___d52) ?
		 2'd0 :
		 ((wrap128_setOffset_cap_BITS_37_TO_35_8_ULT_wrap_ETC___d49 &&
		   !IF_wrap128_setOffset_cap_BITS_43_TO_38_EQ_52_6_ETC___d52) ?
		    2'd1 :
		    2'd3),
	       (wrap128_setOffset_cap_BITS_23_TO_21_6_ULT_wrap_ETC___d50 ==
		IF_wrap128_setOffset_cap_BITS_43_TO_38_EQ_52_6_ETC___d52) ?
		 2'd0 :
		 ((wrap128_setOffset_cap_BITS_23_TO_21_6_ULT_wrap_ETC___d50 &&
		   !IF_wrap128_setOffset_cap_BITS_43_TO_38_EQ_52_6_ETC___d52) ?
		    2'd1 :
		    2'd3) } ;
  assign IF_wrap128_setOffset_cap_BITS_43_TO_38_EQ_52_6_ETC___d52 =
	     result_d_addrBits__h785[13:11] < repBound__h1035 ;
  assign IF_wrap128_setOffset_offset_BIT_63_THEN_NOT_wr_ETC___d19 =
	     wrap128_setOffset_offset[63] ?
	       x__h701[13:0] >= toBounds__h82 :
	       x__h701[13:0] <= toBoundsM1__h83 ;
  assign addBase__h804 =
	     { {48{x__h855[15]}}, x__h855 } << wrap128_setOffset_cap[43:38] ;
  assign highOffsetBits__h73 = x__h100 & mask__h805 ;
  assign mask__h805 = 50'h3FFFFFFFFFFFF << wrap128_setOffset_cap[43:38] ;
  assign newAddrBits__h772 = wrap128_setOffset_cap[23:10] + x__h701[13:0] ;
  assign repBound__h1035 = wrap128_setOffset_cap[23:21] - 3'b001 ;
  assign result_d_addrBits__h785 =
	     { mask__h773, 12'd4095 } & newAddrBits__h772 ;
  assign result_d_address__h784 =
	     { wrap128_setOffset_cap[159:110] & mask__h805, 14'd0 } +
	     addBase__h804 +
	     wrap128_setOffset_offset ;
  assign signBits__h70 = {50{wrap128_setOffset_offset[63]}} ;
  assign toBoundsM1__h83 = { 3'b110, ~wrap128_setOffset_cap[20:10] } ;
  assign toBounds__h82 = 14'd14336 - { 3'b0, wrap128_setOffset_cap[20:10] } ;
  assign wrap128_setOffset_cap_BITS_23_TO_21_6_ULT_wrap_ETC___d50 =
	     wrap128_setOffset_cap[23:21] < repBound__h1035 ;
  assign wrap128_setOffset_cap_BITS_37_TO_35_8_ULT_wrap_ETC___d49 =
	     wrap128_setOffset_cap[37:35] < repBound__h1035 ;
  assign x__h100 = wrap128_setOffset_offset[63:14] ^ signBits__h70 ;
  assign x__h701 = wrap128_setOffset_offset >> wrap128_setOffset_cap[43:38] ;
  assign x__h855 =
	     { wrap128_setOffset_cap[1:0], wrap128_setOffset_cap[23:10] } ;
  always@(wrap128_setOffset_cap)
  begin
    case (wrap128_setOffset_cap[43:38])
      6'd51: mask__h773 = 2'b01;
      6'd52: mask__h773 = 2'b0;
      default: mask__h773 = 2'b11;
    endcase
  end
endmodule  // module_wrap128_setOffset

