//
// Generated by Bluespec Compiler, version 2024.07 (build b4f31db)
//
// On Fri Mar 13 11:37:58 CET 2026
//
//
// Ports:
// Name                         I/O  size props
// wrap128_setBounds              O   162
// wrap128_setBounds_cap          I   161
// wrap128_setBounds_length       I    64
//
// Combinational paths from inputs to outputs:
//   (wrap128_setBounds_cap, wrap128_setBounds_length) -> wrap128_setBounds
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_wrap128_setBounds(wrap128_setBounds_cap,
				wrap128_setBounds_length,
				wrap128_setBounds);
  // value method wrap128_setBounds
  input  [160 : 0] wrap128_setBounds_cap;
  input  [63 : 0] wrap128_setBounds_length;
  output [161 : 0] wrap128_setBounds;

  // signals for module outputs
  wire [161 : 0] wrap128_setBounds;

  // remaining internal signals
  wire [65 : 0] base__h115,
		len__h117,
		lmaskLo__h123,
		lmaskLor__h122,
		mwLsbMask__h131,
		top__h118,
		x__h8717,
		x__h8832,
		x__h9013,
		y__h8718;
  wire [63 : 0] wrap128_setBounds_length_AND_1023_CONCAT_INV_w_ETC___d191,
		wrap128_setBounds_length_OR_0_CONCAT_wrap128_s_ETC___d10,
		wrap128_setBounds_length_OR_0_CONCAT_wrap128_s_ETC___d13,
		wrap128_setBounds_length_OR_0_CONCAT_wrap128_s_ETC___d16,
		wrap128_setBounds_length_OR_0_CONCAT_wrap128_s_ETC___d19,
		wrap128_setBounds_length_OR_0_CONCAT_wrap128_s_ETC___d4,
		wrap128_setBounds_length_OR_0_CONCAT_wrap128_s_ETC___d7;
  wire [27 : 0] IF_NOT_wrap128_setBounds_length_BIT_63_4_5_AND_ETC___d344;
  wire [14 : 0] x__h9052;
  wire [13 : 0] _theResult_____3_fst_bounds_topBits__h8821,
		result_cap_addrBits__h8660,
		ret_bounds_baseBits__h8995,
		ret_bounds_topBits__h8817,
		ret_bounds_topBits__h9044,
		x__h9088,
		x__h9091;
  wire [5 : 0] IF_wrap128_setBounds_length_AND_1023_CONCAT_IN_ETC___d322,
	       _51_MINUS_IF_wrap128_setBounds_length_BIT_63_4__ETC___d315;
  wire [3 : 0] IF_IF_NOT_wrap128_setBounds_length_BIT_63_4_5__ETC___d366;
  wire [2 : 0] repBound__h9081;
  wire IF_NOT_wrap128_setBounds_length_BIT_63_4_5_AND_ETC___d353,
       IF_NOT_wrap128_setBounds_length_BIT_63_4_5_AND_ETC___d354,
       IF_wrap128_setBounds_length_AND_1023_CONCAT_IN_ETC___d356,
       NOT_0_CONCAT_wrap128_setBounds_length_OR_0_CON_ETC___d203,
       NOT_0b0_CONCAT_wrap128_setBounds_cap_BITS_159__ETC___d323,
       NOT_0b0_CONCAT_wrap128_setBounds_cap_BITS_159__ETC___d334,
       _0b0_CONCAT_wrap128_setBounds_cap_BITS_159_TO_9_ETC___d186,
       wrap128_setBounds_cap_BITS_159_TO_96_AND_0_CON_ETC___d179,
       wrap128_setBounds_length_AND_1023_CONCAT_INV_w_ETC___d204,
       wrap128_setBounds_length_AND_1023_CONCAT_INV_w_ETC___d210,
       wrap128_setBounds_length_AND_1023_CONCAT_INV_w_ETC___d211;

  // value method wrap128_setBounds
  assign wrap128_setBounds =
	     { wrap128_setBounds_cap_BITS_159_TO_96_AND_0_CON_ETC___d179 &&
	       _0b0_CONCAT_wrap128_setBounds_cap_BITS_159_TO_9_ETC___d186,
	       wrap128_setBounds_cap[160:96],
	       result_cap_addrBits__h8660,
	       wrap128_setBounds_cap[81:45],
	       wrap128_setBounds_length[63] || wrap128_setBounds_length[62] ||
	       wrap128_setBounds_length[61] ||
	       wrap128_setBounds_length[60] ||
	       wrap128_setBounds_length[59] ||
	       wrap128_setBounds_length[58] ||
	       wrap128_setBounds_length[57] ||
	       wrap128_setBounds_length[56] ||
	       wrap128_setBounds_length[55] ||
	       wrap128_setBounds_length[54] ||
	       wrap128_setBounds_length[53] ||
	       wrap128_setBounds_length[52] ||
	       wrap128_setBounds_length[51] ||
	       wrap128_setBounds_length[50] ||
	       wrap128_setBounds_length[49] ||
	       wrap128_setBounds_length[48] ||
	       wrap128_setBounds_length[47] ||
	       wrap128_setBounds_length[46] ||
	       wrap128_setBounds_length[45] ||
	       wrap128_setBounds_length[44] ||
	       wrap128_setBounds_length[43] ||
	       wrap128_setBounds_length[42] ||
	       wrap128_setBounds_length[41] ||
	       wrap128_setBounds_length[40] ||
	       wrap128_setBounds_length[39] ||
	       wrap128_setBounds_length[38] ||
	       wrap128_setBounds_length[37] ||
	       wrap128_setBounds_length[36] ||
	       wrap128_setBounds_length[35] ||
	       wrap128_setBounds_length[34] ||
	       wrap128_setBounds_length[33] ||
	       wrap128_setBounds_length[32] ||
	       wrap128_setBounds_length[31] ||
	       wrap128_setBounds_length[30] ||
	       wrap128_setBounds_length[29] ||
	       wrap128_setBounds_length[28] ||
	       wrap128_setBounds_length[27] ||
	       wrap128_setBounds_length[26] ||
	       wrap128_setBounds_length[25] ||
	       wrap128_setBounds_length[24] ||
	       wrap128_setBounds_length[23] ||
	       wrap128_setBounds_length[22] ||
	       wrap128_setBounds_length[21] ||
	       wrap128_setBounds_length[20] ||
	       wrap128_setBounds_length[19] ||
	       wrap128_setBounds_length[18] ||
	       wrap128_setBounds_length[17] ||
	       wrap128_setBounds_length[16] ||
	       wrap128_setBounds_length[15] ||
	       wrap128_setBounds_length[14] ||
	       wrap128_setBounds_length[13] ||
	       wrap128_setBounds_length[12],
	       IF_wrap128_setBounds_length_AND_1023_CONCAT_IN_ETC___d322,
	       IF_NOT_wrap128_setBounds_length_BIT_63_4_5_AND_ETC___d344,
	       repBound__h9081,
	       IF_NOT_wrap128_setBounds_length_BIT_63_4_5_AND_ETC___d353,
	       IF_NOT_wrap128_setBounds_length_BIT_63_4_5_AND_ETC___d354,
	       IF_wrap128_setBounds_length_AND_1023_CONCAT_IN_ETC___d356,
	       IF_IF_NOT_wrap128_setBounds_length_BIT_63_4_5__ETC___d366 } ;

  // remaining internal signals
  assign IF_IF_NOT_wrap128_setBounds_length_BIT_63_4_5__ETC___d366 =
	     { (IF_NOT_wrap128_setBounds_length_BIT_63_4_5_AND_ETC___d353 ==
		IF_wrap128_setBounds_length_AND_1023_CONCAT_IN_ETC___d356) ?
		 2'd0 :
		 ((IF_NOT_wrap128_setBounds_length_BIT_63_4_5_AND_ETC___d353 &&
		   !IF_wrap128_setBounds_length_AND_1023_CONCAT_IN_ETC___d356) ?
		    2'd1 :
		    2'd3),
	       (IF_NOT_wrap128_setBounds_length_BIT_63_4_5_AND_ETC___d354 ==
		IF_wrap128_setBounds_length_AND_1023_CONCAT_IN_ETC___d356) ?
		 2'd0 :
		 ((IF_NOT_wrap128_setBounds_length_BIT_63_4_5_AND_ETC___d354 &&
		   !IF_wrap128_setBounds_length_AND_1023_CONCAT_IN_ETC___d356) ?
		    2'd1 :
		    2'd3) } ;
  assign IF_NOT_wrap128_setBounds_length_BIT_63_4_5_AND_ETC___d344 =
	     (!wrap128_setBounds_length[63] &&
	      !wrap128_setBounds_length[62] &&
	      !wrap128_setBounds_length[61] &&
	      !wrap128_setBounds_length[60] &&
	      !wrap128_setBounds_length[59] &&
	      !wrap128_setBounds_length[58] &&
	      !wrap128_setBounds_length[57] &&
	      !wrap128_setBounds_length[56] &&
	      !wrap128_setBounds_length[55] &&
	      !wrap128_setBounds_length[54] &&
	      !wrap128_setBounds_length[53] &&
	      !wrap128_setBounds_length[52] &&
	      !wrap128_setBounds_length[51] &&
	      !wrap128_setBounds_length[50] &&
	      !wrap128_setBounds_length[49] &&
	      !wrap128_setBounds_length[48] &&
	      !wrap128_setBounds_length[47] &&
	      !wrap128_setBounds_length[46] &&
	      !wrap128_setBounds_length[45] &&
	      !wrap128_setBounds_length[44] &&
	      !wrap128_setBounds_length[43] &&
	      !wrap128_setBounds_length[42] &&
	      !wrap128_setBounds_length[41] &&
	      !wrap128_setBounds_length[40] &&
	      !wrap128_setBounds_length[39] &&
	      !wrap128_setBounds_length[38] &&
	      !wrap128_setBounds_length[37] &&
	      !wrap128_setBounds_length[36] &&
	      !wrap128_setBounds_length[35] &&
	      !wrap128_setBounds_length[34] &&
	      !wrap128_setBounds_length[33] &&
	      !wrap128_setBounds_length[32] &&
	      !wrap128_setBounds_length[31] &&
	      !wrap128_setBounds_length[30] &&
	      !wrap128_setBounds_length[29] &&
	      !wrap128_setBounds_length[28] &&
	      !wrap128_setBounds_length[27] &&
	      !wrap128_setBounds_length[26] &&
	      !wrap128_setBounds_length[25] &&
	      !wrap128_setBounds_length[24] &&
	      !wrap128_setBounds_length[23] &&
	      !wrap128_setBounds_length[22] &&
	      !wrap128_setBounds_length[21] &&
	      !wrap128_setBounds_length[20] &&
	      !wrap128_setBounds_length[19] &&
	      !wrap128_setBounds_length[18] &&
	      !wrap128_setBounds_length[17] &&
	      !wrap128_setBounds_length[16] &&
	      !wrap128_setBounds_length[15] &&
	      !wrap128_setBounds_length[14] &&
	      !wrap128_setBounds_length[13] &&
	      !wrap128_setBounds_length[12]) ?
	       { ret_bounds_topBits__h9044, x__h8832[13:0] } :
	       { ret_bounds_topBits__h8817[13:3],
		 3'd0,
		 ret_bounds_baseBits__h8995 } ;
  assign IF_NOT_wrap128_setBounds_length_BIT_63_4_5_AND_ETC___d353 =
	     x__h9091[13:11] < repBound__h9081 ;
  assign IF_NOT_wrap128_setBounds_length_BIT_63_4_5_AND_ETC___d354 =
	     x__h9088[13:11] < repBound__h9081 ;
  assign IF_wrap128_setBounds_length_AND_1023_CONCAT_IN_ETC___d322 =
	     (wrap128_setBounds_length_AND_1023_CONCAT_INV_w_ETC___d211 &&
	      (wrap128_setBounds_length[63] || wrap128_setBounds_length[62] ||
	       wrap128_setBounds_length[61] ||
	       wrap128_setBounds_length[60] ||
	       wrap128_setBounds_length[59] ||
	       wrap128_setBounds_length[58] ||
	       wrap128_setBounds_length[57] ||
	       wrap128_setBounds_length[56] ||
	       wrap128_setBounds_length[55] ||
	       wrap128_setBounds_length[54] ||
	       wrap128_setBounds_length[53] ||
	       wrap128_setBounds_length[52] ||
	       wrap128_setBounds_length[51] ||
	       wrap128_setBounds_length[50] ||
	       wrap128_setBounds_length[49] ||
	       wrap128_setBounds_length[48] ||
	       wrap128_setBounds_length[47] ||
	       wrap128_setBounds_length[46] ||
	       wrap128_setBounds_length[45] ||
	       wrap128_setBounds_length[44] ||
	       wrap128_setBounds_length[43] ||
	       wrap128_setBounds_length[42] ||
	       wrap128_setBounds_length[41] ||
	       wrap128_setBounds_length[40] ||
	       wrap128_setBounds_length[39] ||
	       wrap128_setBounds_length[38] ||
	       wrap128_setBounds_length[37] ||
	       wrap128_setBounds_length[36] ||
	       wrap128_setBounds_length[35] ||
	       wrap128_setBounds_length[34] ||
	       wrap128_setBounds_length[33] ||
	       wrap128_setBounds_length[32] ||
	       wrap128_setBounds_length[31] ||
	       wrap128_setBounds_length[30] ||
	       wrap128_setBounds_length[29] ||
	       wrap128_setBounds_length[28] ||
	       wrap128_setBounds_length[27] ||
	       wrap128_setBounds_length[26] ||
	       wrap128_setBounds_length[25] ||
	       wrap128_setBounds_length[24] ||
	       wrap128_setBounds_length[23] ||
	       wrap128_setBounds_length[22] ||
	       wrap128_setBounds_length[21] ||
	       wrap128_setBounds_length[20] ||
	       wrap128_setBounds_length[19] ||
	       wrap128_setBounds_length[18] ||
	       wrap128_setBounds_length[17] ||
	       wrap128_setBounds_length[16] ||
	       wrap128_setBounds_length[15] ||
	       wrap128_setBounds_length[14] ||
	       wrap128_setBounds_length[13] ||
	       wrap128_setBounds_length[12])) ?
	       _51_MINUS_IF_wrap128_setBounds_length_BIT_63_4__ETC___d315 +
	       6'd1 :
	       _51_MINUS_IF_wrap128_setBounds_length_BIT_63_4__ETC___d315 ;
  assign IF_wrap128_setBounds_length_AND_1023_CONCAT_IN_ETC___d356 =
	     result_cap_addrBits__h8660[13:11] < repBound__h9081 ;
  assign NOT_0_CONCAT_wrap128_setBounds_length_OR_0_CON_ETC___d203 =
	     (mwLsbMask__h131 & top__h118) != (x__h8717 ^ y__h8718) ;
  assign NOT_0b0_CONCAT_wrap128_setBounds_cap_BITS_159__ETC___d323 =
	     (top__h118 & lmaskLor__h122) != 66'd0 &&
	     (wrap128_setBounds_length[63] || wrap128_setBounds_length[62] ||
	      wrap128_setBounds_length[61] ||
	      wrap128_setBounds_length[60] ||
	      wrap128_setBounds_length[59] ||
	      wrap128_setBounds_length[58] ||
	      wrap128_setBounds_length[57] ||
	      wrap128_setBounds_length[56] ||
	      wrap128_setBounds_length[55] ||
	      wrap128_setBounds_length[54] ||
	      wrap128_setBounds_length[53] ||
	      wrap128_setBounds_length[52] ||
	      wrap128_setBounds_length[51] ||
	      wrap128_setBounds_length[50] ||
	      wrap128_setBounds_length[49] ||
	      wrap128_setBounds_length[48] ||
	      wrap128_setBounds_length[47] ||
	      wrap128_setBounds_length[46] ||
	      wrap128_setBounds_length[45] ||
	      wrap128_setBounds_length[44] ||
	      wrap128_setBounds_length[43] ||
	      wrap128_setBounds_length[42] ||
	      wrap128_setBounds_length[41] ||
	      wrap128_setBounds_length[40] ||
	      wrap128_setBounds_length[39] ||
	      wrap128_setBounds_length[38] ||
	      wrap128_setBounds_length[37] ||
	      wrap128_setBounds_length[36] ||
	      wrap128_setBounds_length[35] ||
	      wrap128_setBounds_length[34] ||
	      wrap128_setBounds_length[33] ||
	      wrap128_setBounds_length[32] ||
	      wrap128_setBounds_length[31] ||
	      wrap128_setBounds_length[30] ||
	      wrap128_setBounds_length[29] ||
	      wrap128_setBounds_length[28] ||
	      wrap128_setBounds_length[27] ||
	      wrap128_setBounds_length[26] ||
	      wrap128_setBounds_length[25] ||
	      wrap128_setBounds_length[24] ||
	      wrap128_setBounds_length[23] ||
	      wrap128_setBounds_length[22] ||
	      wrap128_setBounds_length[21] ||
	      wrap128_setBounds_length[20] ||
	      wrap128_setBounds_length[19] ||
	      wrap128_setBounds_length[18] ||
	      wrap128_setBounds_length[17] ||
	      wrap128_setBounds_length[16] ||
	      wrap128_setBounds_length[15] ||
	      wrap128_setBounds_length[14] ||
	      wrap128_setBounds_length[13] ||
	      wrap128_setBounds_length[12]) ;
  assign NOT_0b0_CONCAT_wrap128_setBounds_cap_BITS_159__ETC___d334 =
	     (top__h118 & lmaskLo__h123) != 66'd0 &&
	     (wrap128_setBounds_length[63] || wrap128_setBounds_length[62] ||
	      wrap128_setBounds_length[61] ||
	      wrap128_setBounds_length[60] ||
	      wrap128_setBounds_length[59] ||
	      wrap128_setBounds_length[58] ||
	      wrap128_setBounds_length[57] ||
	      wrap128_setBounds_length[56] ||
	      wrap128_setBounds_length[55] ||
	      wrap128_setBounds_length[54] ||
	      wrap128_setBounds_length[53] ||
	      wrap128_setBounds_length[52] ||
	      wrap128_setBounds_length[51] ||
	      wrap128_setBounds_length[50] ||
	      wrap128_setBounds_length[49] ||
	      wrap128_setBounds_length[48] ||
	      wrap128_setBounds_length[47] ||
	      wrap128_setBounds_length[46] ||
	      wrap128_setBounds_length[45] ||
	      wrap128_setBounds_length[44] ||
	      wrap128_setBounds_length[43] ||
	      wrap128_setBounds_length[42] ||
	      wrap128_setBounds_length[41] ||
	      wrap128_setBounds_length[40] ||
	      wrap128_setBounds_length[39] ||
	      wrap128_setBounds_length[38] ||
	      wrap128_setBounds_length[37] ||
	      wrap128_setBounds_length[36] ||
	      wrap128_setBounds_length[35] ||
	      wrap128_setBounds_length[34] ||
	      wrap128_setBounds_length[33] ||
	      wrap128_setBounds_length[32] ||
	      wrap128_setBounds_length[31] ||
	      wrap128_setBounds_length[30] ||
	      wrap128_setBounds_length[29] ||
	      wrap128_setBounds_length[28] ||
	      wrap128_setBounds_length[27] ||
	      wrap128_setBounds_length[26] ||
	      wrap128_setBounds_length[25] ||
	      wrap128_setBounds_length[24] ||
	      wrap128_setBounds_length[23] ||
	      wrap128_setBounds_length[22] ||
	      wrap128_setBounds_length[21] ||
	      wrap128_setBounds_length[20] ||
	      wrap128_setBounds_length[19] ||
	      wrap128_setBounds_length[18] ||
	      wrap128_setBounds_length[17] ||
	      wrap128_setBounds_length[16] ||
	      wrap128_setBounds_length[15] ||
	      wrap128_setBounds_length[14] ||
	      wrap128_setBounds_length[13] ||
	      wrap128_setBounds_length[12]) ;
  assign _0b0_CONCAT_wrap128_setBounds_cap_BITS_159_TO_9_ETC___d186 =
	     (top__h118 & lmaskLor__h122) == 66'd0 ||
	     !wrap128_setBounds_length[63] && !wrap128_setBounds_length[62] &&
	     !wrap128_setBounds_length[61] &&
	     !wrap128_setBounds_length[60] &&
	     !wrap128_setBounds_length[59] &&
	     !wrap128_setBounds_length[58] &&
	     !wrap128_setBounds_length[57] &&
	     !wrap128_setBounds_length[56] &&
	     !wrap128_setBounds_length[55] &&
	     !wrap128_setBounds_length[54] &&
	     !wrap128_setBounds_length[53] &&
	     !wrap128_setBounds_length[52] &&
	     !wrap128_setBounds_length[51] &&
	     !wrap128_setBounds_length[50] &&
	     !wrap128_setBounds_length[49] &&
	     !wrap128_setBounds_length[48] &&
	     !wrap128_setBounds_length[47] &&
	     !wrap128_setBounds_length[46] &&
	     !wrap128_setBounds_length[45] &&
	     !wrap128_setBounds_length[44] &&
	     !wrap128_setBounds_length[43] &&
	     !wrap128_setBounds_length[42] &&
	     !wrap128_setBounds_length[41] &&
	     !wrap128_setBounds_length[40] &&
	     !wrap128_setBounds_length[39] &&
	     !wrap128_setBounds_length[38] &&
	     !wrap128_setBounds_length[37] &&
	     !wrap128_setBounds_length[36] &&
	     !wrap128_setBounds_length[35] &&
	     !wrap128_setBounds_length[34] &&
	     !wrap128_setBounds_length[33] &&
	     !wrap128_setBounds_length[32] &&
	     !wrap128_setBounds_length[31] &&
	     !wrap128_setBounds_length[30] &&
	     !wrap128_setBounds_length[29] &&
	     !wrap128_setBounds_length[28] &&
	     !wrap128_setBounds_length[27] &&
	     !wrap128_setBounds_length[26] &&
	     !wrap128_setBounds_length[25] &&
	     !wrap128_setBounds_length[24] &&
	     !wrap128_setBounds_length[23] &&
	     !wrap128_setBounds_length[22] &&
	     !wrap128_setBounds_length[21] &&
	     !wrap128_setBounds_length[20] &&
	     !wrap128_setBounds_length[19] &&
	     !wrap128_setBounds_length[18] &&
	     !wrap128_setBounds_length[17] &&
	     !wrap128_setBounds_length[16] &&
	     !wrap128_setBounds_length[15] &&
	     !wrap128_setBounds_length[14] &&
	     !wrap128_setBounds_length[13] &&
	     !wrap128_setBounds_length[12] ;
  assign _51_MINUS_IF_wrap128_setBounds_length_BIT_63_4__ETC___d315 =
	     6'd51 -
	     (wrap128_setBounds_length[63] ?
		6'd0 :
		(wrap128_setBounds_length[62] ?
		   6'd1 :
		   (wrap128_setBounds_length[61] ?
		      6'd2 :
		      (wrap128_setBounds_length[60] ?
			 6'd3 :
			 (wrap128_setBounds_length[59] ?
			    6'd4 :
			    (wrap128_setBounds_length[58] ?
			       6'd5 :
			       (wrap128_setBounds_length[57] ?
				  6'd6 :
				  (wrap128_setBounds_length[56] ?
				     6'd7 :
				     (wrap128_setBounds_length[55] ?
					6'd8 :
					(wrap128_setBounds_length[54] ?
					   6'd9 :
					   (wrap128_setBounds_length[53] ?
					      6'd10 :
					      (wrap128_setBounds_length[52] ?
						 6'd11 :
						 (wrap128_setBounds_length[51] ?
						    6'd12 :
						    (wrap128_setBounds_length[50] ?
						       6'd13 :
						       (wrap128_setBounds_length[49] ?
							  6'd14 :
							  (wrap128_setBounds_length[48] ?
							     6'd15 :
							     (wrap128_setBounds_length[47] ?
								6'd16 :
								(wrap128_setBounds_length[46] ?
								   6'd17 :
								   (wrap128_setBounds_length[45] ?
								      6'd18 :
								      (wrap128_setBounds_length[44] ?
									 6'd19 :
									 (wrap128_setBounds_length[43] ?
									    6'd20 :
									    (wrap128_setBounds_length[42] ?
									       6'd21 :
									       (wrap128_setBounds_length[41] ?
										  6'd22 :
										  (wrap128_setBounds_length[40] ?
										     6'd23 :
										     (wrap128_setBounds_length[39] ?
											6'd24 :
											(wrap128_setBounds_length[38] ?
											   6'd25 :
											   (wrap128_setBounds_length[37] ?
											      6'd26 :
											      (wrap128_setBounds_length[36] ?
												 6'd27 :
												 (wrap128_setBounds_length[35] ?
												    6'd28 :
												    (wrap128_setBounds_length[34] ?
												       6'd29 :
												       (wrap128_setBounds_length[33] ?
													  6'd30 :
													  (wrap128_setBounds_length[32] ?
													     6'd31 :
													     (wrap128_setBounds_length[31] ?
														6'd32 :
														(wrap128_setBounds_length[30] ?
														   6'd33 :
														   (wrap128_setBounds_length[29] ?
														      6'd34 :
														      (wrap128_setBounds_length[28] ?
															 6'd35 :
															 (wrap128_setBounds_length[27] ?
															    6'd36 :
															    (wrap128_setBounds_length[26] ?
															       6'd37 :
															       (wrap128_setBounds_length[25] ?
																  6'd38 :
																  (wrap128_setBounds_length[24] ?
																     6'd39 :
																     (wrap128_setBounds_length[23] ?
																	6'd40 :
																	(wrap128_setBounds_length[22] ?
																	   6'd41 :
																	   (wrap128_setBounds_length[21] ?
																	      6'd42 :
																	      (wrap128_setBounds_length[20] ?
																		 6'd43 :
																		 (wrap128_setBounds_length[19] ?
																		    6'd44 :
																		    (wrap128_setBounds_length[18] ?
																		       6'd45 :
																		       (wrap128_setBounds_length[17] ?
																			  6'd46 :
																			  (wrap128_setBounds_length[16] ?
																			     6'd47 :
																			     (wrap128_setBounds_length[15] ?
																				6'd48 :
																				(wrap128_setBounds_length[14] ?
																				   6'd49 :
																				   (wrap128_setBounds_length[13] ?
																				      6'd50 :
																				      6'd51))))))))))))))))))))))))))))))))))))))))))))))))))) ;
  assign _theResult_____3_fst_bounds_topBits__h8821 =
	     NOT_0b0_CONCAT_wrap128_setBounds_cap_BITS_159__ETC___d334 ?
	       x__h9013[14:1] + 14'b00000000001000 :
	       x__h9013[14:1] ;
  assign base__h115 = { 2'b0, wrap128_setBounds_cap[159:96] } ;
  assign len__h117 = { 2'b0, wrap128_setBounds_length } ;
  assign lmaskLo__h123 =
	     { 11'd0,
	       wrap128_setBounds_length_OR_0_CONCAT_wrap128_s_ETC___d19[63:9] } ;
  assign lmaskLor__h122 =
	     { 12'd0,
	       wrap128_setBounds_length_OR_0_CONCAT_wrap128_s_ETC___d19[63:10] } ;
  assign mwLsbMask__h131 = lmaskLor__h122 ^ lmaskLo__h123 ;
  assign repBound__h9081 = x__h9088[13:11] - 3'b001 ;
  assign result_cap_addrBits__h8660 =
	     (wrap128_setBounds_length_AND_1023_CONCAT_INV_w_ETC___d211 &&
	      (wrap128_setBounds_length[63] || wrap128_setBounds_length[62] ||
	       wrap128_setBounds_length[61] ||
	       wrap128_setBounds_length[60] ||
	       wrap128_setBounds_length[59] ||
	       wrap128_setBounds_length[58] ||
	       wrap128_setBounds_length[57] ||
	       wrap128_setBounds_length[56] ||
	       wrap128_setBounds_length[55] ||
	       wrap128_setBounds_length[54] ||
	       wrap128_setBounds_length[53] ||
	       wrap128_setBounds_length[52] ||
	       wrap128_setBounds_length[51] ||
	       wrap128_setBounds_length[50] ||
	       wrap128_setBounds_length[49] ||
	       wrap128_setBounds_length[48] ||
	       wrap128_setBounds_length[47] ||
	       wrap128_setBounds_length[46] ||
	       wrap128_setBounds_length[45] ||
	       wrap128_setBounds_length[44] ||
	       wrap128_setBounds_length[43] ||
	       wrap128_setBounds_length[42] ||
	       wrap128_setBounds_length[41] ||
	       wrap128_setBounds_length[40] ||
	       wrap128_setBounds_length[39] ||
	       wrap128_setBounds_length[38] ||
	       wrap128_setBounds_length[37] ||
	       wrap128_setBounds_length[36] ||
	       wrap128_setBounds_length[35] ||
	       wrap128_setBounds_length[34] ||
	       wrap128_setBounds_length[33] ||
	       wrap128_setBounds_length[32] ||
	       wrap128_setBounds_length[31] ||
	       wrap128_setBounds_length[30] ||
	       wrap128_setBounds_length[29] ||
	       wrap128_setBounds_length[28] ||
	       wrap128_setBounds_length[27] ||
	       wrap128_setBounds_length[26] ||
	       wrap128_setBounds_length[25] ||
	       wrap128_setBounds_length[24] ||
	       wrap128_setBounds_length[23] ||
	       wrap128_setBounds_length[22] ||
	       wrap128_setBounds_length[21] ||
	       wrap128_setBounds_length[20] ||
	       wrap128_setBounds_length[19] ||
	       wrap128_setBounds_length[18] ||
	       wrap128_setBounds_length[17] ||
	       wrap128_setBounds_length[16] ||
	       wrap128_setBounds_length[15] ||
	       wrap128_setBounds_length[14] ||
	       wrap128_setBounds_length[13] ||
	       wrap128_setBounds_length[12])) ?
	       x__h8832[14:1] :
	       x__h8832[13:0] ;
  assign ret_bounds_baseBits__h8995 =
	     { result_cap_addrBits__h8660[13:3], 3'd0 } ;
  assign ret_bounds_topBits__h8817 =
	     (wrap128_setBounds_length_AND_1023_CONCAT_INV_w_ETC___d211 &&
	      (wrap128_setBounds_length[63] || wrap128_setBounds_length[62] ||
	       wrap128_setBounds_length[61] ||
	       wrap128_setBounds_length[60] ||
	       wrap128_setBounds_length[59] ||
	       wrap128_setBounds_length[58] ||
	       wrap128_setBounds_length[57] ||
	       wrap128_setBounds_length[56] ||
	       wrap128_setBounds_length[55] ||
	       wrap128_setBounds_length[54] ||
	       wrap128_setBounds_length[53] ||
	       wrap128_setBounds_length[52] ||
	       wrap128_setBounds_length[51] ||
	       wrap128_setBounds_length[50] ||
	       wrap128_setBounds_length[49] ||
	       wrap128_setBounds_length[48] ||
	       wrap128_setBounds_length[47] ||
	       wrap128_setBounds_length[46] ||
	       wrap128_setBounds_length[45] ||
	       wrap128_setBounds_length[44] ||
	       wrap128_setBounds_length[43] ||
	       wrap128_setBounds_length[42] ||
	       wrap128_setBounds_length[41] ||
	       wrap128_setBounds_length[40] ||
	       wrap128_setBounds_length[39] ||
	       wrap128_setBounds_length[38] ||
	       wrap128_setBounds_length[37] ||
	       wrap128_setBounds_length[36] ||
	       wrap128_setBounds_length[35] ||
	       wrap128_setBounds_length[34] ||
	       wrap128_setBounds_length[33] ||
	       wrap128_setBounds_length[32] ||
	       wrap128_setBounds_length[31] ||
	       wrap128_setBounds_length[30] ||
	       wrap128_setBounds_length[29] ||
	       wrap128_setBounds_length[28] ||
	       wrap128_setBounds_length[27] ||
	       wrap128_setBounds_length[26] ||
	       wrap128_setBounds_length[25] ||
	       wrap128_setBounds_length[24] ||
	       wrap128_setBounds_length[23] ||
	       wrap128_setBounds_length[22] ||
	       wrap128_setBounds_length[21] ||
	       wrap128_setBounds_length[20] ||
	       wrap128_setBounds_length[19] ||
	       wrap128_setBounds_length[18] ||
	       wrap128_setBounds_length[17] ||
	       wrap128_setBounds_length[16] ||
	       wrap128_setBounds_length[15] ||
	       wrap128_setBounds_length[14] ||
	       wrap128_setBounds_length[13] ||
	       wrap128_setBounds_length[12])) ?
	       _theResult_____3_fst_bounds_topBits__h8821 :
	       ret_bounds_topBits__h9044 ;
  assign ret_bounds_topBits__h9044 =
	     NOT_0b0_CONCAT_wrap128_setBounds_cap_BITS_159__ETC___d323 ?
	       x__h9052[13:0] :
	       x__h9013[13:0] ;
  assign top__h118 = base__h115 + len__h117 ;
  assign wrap128_setBounds_cap_BITS_159_TO_96_AND_0_CON_ETC___d179 =
	     (wrap128_setBounds_cap[159:96] &
	      { 10'd0,
		wrap128_setBounds_length_OR_0_CONCAT_wrap128_s_ETC___d19[63:10] }) ==
	     64'd0 ||
	     !wrap128_setBounds_length[63] && !wrap128_setBounds_length[62] &&
	     !wrap128_setBounds_length[61] &&
	     !wrap128_setBounds_length[60] &&
	     !wrap128_setBounds_length[59] &&
	     !wrap128_setBounds_length[58] &&
	     !wrap128_setBounds_length[57] &&
	     !wrap128_setBounds_length[56] &&
	     !wrap128_setBounds_length[55] &&
	     !wrap128_setBounds_length[54] &&
	     !wrap128_setBounds_length[53] &&
	     !wrap128_setBounds_length[52] &&
	     !wrap128_setBounds_length[51] &&
	     !wrap128_setBounds_length[50] &&
	     !wrap128_setBounds_length[49] &&
	     !wrap128_setBounds_length[48] &&
	     !wrap128_setBounds_length[47] &&
	     !wrap128_setBounds_length[46] &&
	     !wrap128_setBounds_length[45] &&
	     !wrap128_setBounds_length[44] &&
	     !wrap128_setBounds_length[43] &&
	     !wrap128_setBounds_length[42] &&
	     !wrap128_setBounds_length[41] &&
	     !wrap128_setBounds_length[40] &&
	     !wrap128_setBounds_length[39] &&
	     !wrap128_setBounds_length[38] &&
	     !wrap128_setBounds_length[37] &&
	     !wrap128_setBounds_length[36] &&
	     !wrap128_setBounds_length[35] &&
	     !wrap128_setBounds_length[34] &&
	     !wrap128_setBounds_length[33] &&
	     !wrap128_setBounds_length[32] &&
	     !wrap128_setBounds_length[31] &&
	     !wrap128_setBounds_length[30] &&
	     !wrap128_setBounds_length[29] &&
	     !wrap128_setBounds_length[28] &&
	     !wrap128_setBounds_length[27] &&
	     !wrap128_setBounds_length[26] &&
	     !wrap128_setBounds_length[25] &&
	     !wrap128_setBounds_length[24] &&
	     !wrap128_setBounds_length[23] &&
	     !wrap128_setBounds_length[22] &&
	     !wrap128_setBounds_length[21] &&
	     !wrap128_setBounds_length[20] &&
	     !wrap128_setBounds_length[19] &&
	     !wrap128_setBounds_length[18] &&
	     !wrap128_setBounds_length[17] &&
	     !wrap128_setBounds_length[16] &&
	     !wrap128_setBounds_length[15] &&
	     !wrap128_setBounds_length[14] &&
	     !wrap128_setBounds_length[13] &&
	     !wrap128_setBounds_length[12] ;
  assign wrap128_setBounds_length_AND_1023_CONCAT_INV_w_ETC___d191 =
	     wrap128_setBounds_length &
	     { 10'd1023,
	       ~wrap128_setBounds_length_OR_0_CONCAT_wrap128_s_ETC___d19[63:10] } ;
  assign wrap128_setBounds_length_AND_1023_CONCAT_INV_w_ETC___d204 =
	     wrap128_setBounds_length_AND_1023_CONCAT_INV_w_ETC___d191 ==
	     (wrap128_setBounds_length_OR_0_CONCAT_wrap128_s_ETC___d19 ^
	      { 9'd0,
		wrap128_setBounds_length_OR_0_CONCAT_wrap128_s_ETC___d19[63:9] }) &&
	     NOT_0_CONCAT_wrap128_setBounds_length_OR_0_CON_ETC___d203 ;
  assign wrap128_setBounds_length_AND_1023_CONCAT_INV_w_ETC___d210 =
	     wrap128_setBounds_length_AND_1023_CONCAT_INV_w_ETC___d191 ==
	     (wrap128_setBounds_length_OR_0_CONCAT_wrap128_s_ETC___d19 ^
	      { 10'd0,
		wrap128_setBounds_length_OR_0_CONCAT_wrap128_s_ETC___d19[63:10] }) &&
	     (NOT_0_CONCAT_wrap128_setBounds_length_OR_0_CON_ETC___d203 ||
	      (top__h118 & lmaskLor__h122) != 66'd0) ;
  assign wrap128_setBounds_length_AND_1023_CONCAT_INV_w_ETC___d211 =
	     wrap128_setBounds_length_AND_1023_CONCAT_INV_w_ETC___d204 &&
	     (top__h118 & lmaskLor__h122) != 66'd0 ||
	     wrap128_setBounds_length_AND_1023_CONCAT_INV_w_ETC___d210 ;
  assign wrap128_setBounds_length_OR_0_CONCAT_wrap128_s_ETC___d10 =
	     wrap128_setBounds_length_OR_0_CONCAT_wrap128_s_ETC___d7 |
	     { 4'd0,
	       wrap128_setBounds_length_OR_0_CONCAT_wrap128_s_ETC___d7[63:4] } ;
  assign wrap128_setBounds_length_OR_0_CONCAT_wrap128_s_ETC___d13 =
	     wrap128_setBounds_length_OR_0_CONCAT_wrap128_s_ETC___d10 |
	     { 8'd0,
	       wrap128_setBounds_length_OR_0_CONCAT_wrap128_s_ETC___d10[63:8] } ;
  assign wrap128_setBounds_length_OR_0_CONCAT_wrap128_s_ETC___d16 =
	     wrap128_setBounds_length_OR_0_CONCAT_wrap128_s_ETC___d13 |
	     { 16'd0,
	       wrap128_setBounds_length_OR_0_CONCAT_wrap128_s_ETC___d13[63:16] } ;
  assign wrap128_setBounds_length_OR_0_CONCAT_wrap128_s_ETC___d19 =
	     wrap128_setBounds_length_OR_0_CONCAT_wrap128_s_ETC___d16 |
	     { 32'd0,
	       wrap128_setBounds_length_OR_0_CONCAT_wrap128_s_ETC___d16[63:32] } ;
  assign wrap128_setBounds_length_OR_0_CONCAT_wrap128_s_ETC___d4 =
	     wrap128_setBounds_length |
	     { 1'd0, wrap128_setBounds_length[63:1] } ;
  assign wrap128_setBounds_length_OR_0_CONCAT_wrap128_s_ETC___d7 =
	     wrap128_setBounds_length_OR_0_CONCAT_wrap128_s_ETC___d4 |
	     { 2'd0,
	       wrap128_setBounds_length_OR_0_CONCAT_wrap128_s_ETC___d4[63:2] } ;
  assign x__h8717 = mwLsbMask__h131 & base__h115 ;
  assign x__h8832 =
	     base__h115 >>
	     _51_MINUS_IF_wrap128_setBounds_length_BIT_63_4__ETC___d315 ;
  assign x__h9013 =
	     top__h118 >>
	     _51_MINUS_IF_wrap128_setBounds_length_BIT_63_4__ETC___d315 ;
  assign x__h9052 = x__h9013[14:0] + 15'b000000000001000 ;
  assign x__h9088 =
	     (!wrap128_setBounds_length[63] &&
	      !wrap128_setBounds_length[62] &&
	      !wrap128_setBounds_length[61] &&
	      !wrap128_setBounds_length[60] &&
	      !wrap128_setBounds_length[59] &&
	      !wrap128_setBounds_length[58] &&
	      !wrap128_setBounds_length[57] &&
	      !wrap128_setBounds_length[56] &&
	      !wrap128_setBounds_length[55] &&
	      !wrap128_setBounds_length[54] &&
	      !wrap128_setBounds_length[53] &&
	      !wrap128_setBounds_length[52] &&
	      !wrap128_setBounds_length[51] &&
	      !wrap128_setBounds_length[50] &&
	      !wrap128_setBounds_length[49] &&
	      !wrap128_setBounds_length[48] &&
	      !wrap128_setBounds_length[47] &&
	      !wrap128_setBounds_length[46] &&
	      !wrap128_setBounds_length[45] &&
	      !wrap128_setBounds_length[44] &&
	      !wrap128_setBounds_length[43] &&
	      !wrap128_setBounds_length[42] &&
	      !wrap128_setBounds_length[41] &&
	      !wrap128_setBounds_length[40] &&
	      !wrap128_setBounds_length[39] &&
	      !wrap128_setBounds_length[38] &&
	      !wrap128_setBounds_length[37] &&
	      !wrap128_setBounds_length[36] &&
	      !wrap128_setBounds_length[35] &&
	      !wrap128_setBounds_length[34] &&
	      !wrap128_setBounds_length[33] &&
	      !wrap128_setBounds_length[32] &&
	      !wrap128_setBounds_length[31] &&
	      !wrap128_setBounds_length[30] &&
	      !wrap128_setBounds_length[29] &&
	      !wrap128_setBounds_length[28] &&
	      !wrap128_setBounds_length[27] &&
	      !wrap128_setBounds_length[26] &&
	      !wrap128_setBounds_length[25] &&
	      !wrap128_setBounds_length[24] &&
	      !wrap128_setBounds_length[23] &&
	      !wrap128_setBounds_length[22] &&
	      !wrap128_setBounds_length[21] &&
	      !wrap128_setBounds_length[20] &&
	      !wrap128_setBounds_length[19] &&
	      !wrap128_setBounds_length[18] &&
	      !wrap128_setBounds_length[17] &&
	      !wrap128_setBounds_length[16] &&
	      !wrap128_setBounds_length[15] &&
	      !wrap128_setBounds_length[14] &&
	      !wrap128_setBounds_length[13] &&
	      !wrap128_setBounds_length[12]) ?
	       result_cap_addrBits__h8660 :
	       ret_bounds_baseBits__h8995 ;
  assign x__h9091 =
	     (!wrap128_setBounds_length[63] &&
	      !wrap128_setBounds_length[62] &&
	      !wrap128_setBounds_length[61] &&
	      !wrap128_setBounds_length[60] &&
	      !wrap128_setBounds_length[59] &&
	      !wrap128_setBounds_length[58] &&
	      !wrap128_setBounds_length[57] &&
	      !wrap128_setBounds_length[56] &&
	      !wrap128_setBounds_length[55] &&
	      !wrap128_setBounds_length[54] &&
	      !wrap128_setBounds_length[53] &&
	      !wrap128_setBounds_length[52] &&
	      !wrap128_setBounds_length[51] &&
	      !wrap128_setBounds_length[50] &&
	      !wrap128_setBounds_length[49] &&
	      !wrap128_setBounds_length[48] &&
	      !wrap128_setBounds_length[47] &&
	      !wrap128_setBounds_length[46] &&
	      !wrap128_setBounds_length[45] &&
	      !wrap128_setBounds_length[44] &&
	      !wrap128_setBounds_length[43] &&
	      !wrap128_setBounds_length[42] &&
	      !wrap128_setBounds_length[41] &&
	      !wrap128_setBounds_length[40] &&
	      !wrap128_setBounds_length[39] &&
	      !wrap128_setBounds_length[38] &&
	      !wrap128_setBounds_length[37] &&
	      !wrap128_setBounds_length[36] &&
	      !wrap128_setBounds_length[35] &&
	      !wrap128_setBounds_length[34] &&
	      !wrap128_setBounds_length[33] &&
	      !wrap128_setBounds_length[32] &&
	      !wrap128_setBounds_length[31] &&
	      !wrap128_setBounds_length[30] &&
	      !wrap128_setBounds_length[29] &&
	      !wrap128_setBounds_length[28] &&
	      !wrap128_setBounds_length[27] &&
	      !wrap128_setBounds_length[26] &&
	      !wrap128_setBounds_length[25] &&
	      !wrap128_setBounds_length[24] &&
	      !wrap128_setBounds_length[23] &&
	      !wrap128_setBounds_length[22] &&
	      !wrap128_setBounds_length[21] &&
	      !wrap128_setBounds_length[20] &&
	      !wrap128_setBounds_length[19] &&
	      !wrap128_setBounds_length[18] &&
	      !wrap128_setBounds_length[17] &&
	      !wrap128_setBounds_length[16] &&
	      !wrap128_setBounds_length[15] &&
	      !wrap128_setBounds_length[14] &&
	      !wrap128_setBounds_length[13] &&
	      !wrap128_setBounds_length[12]) ?
	       ret_bounds_topBits__h8817 :
	       { ret_bounds_topBits__h8817[13:3], 3'd0 } ;
  assign y__h8718 = mwLsbMask__h131 & len__h117 ;
endmodule  // module_wrap128_setBounds

