//
// Generated by Bluespec Compiler, version 2024.07 (build b4f31db)
//
// On Fri Mar 13 11:37:57 CET 2026
//
//
// Ports:
// Name                         I/O  size props
// wrap128_modifyOffset           O   162
// wrap128_modifyOffset_cap       I   161
// wrap128_modifyOffset_offset    I    64
// wrap128_modifyOffset_doInc     I     1
//
// Combinational paths from inputs to outputs:
//   (wrap128_modifyOffset_cap,
//    wrap128_modifyOffset_offset,
//    wrap128_modifyOffset_doInc) -> wrap128_modifyOffset
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_wrap128_modifyOffset(wrap128_modifyOffset_cap,
				   wrap128_modifyOffset_offset,
				   wrap128_modifyOffset_doInc,
				   wrap128_modifyOffset);
  // value method wrap128_modifyOffset
  input  [160 : 0] wrap128_modifyOffset_cap;
  input  [63 : 0] wrap128_modifyOffset_offset;
  input  wrap128_modifyOffset_doInc;
  output [161 : 0] wrap128_modifyOffset;

  // signals for module outputs
  wire [161 : 0] wrap128_modifyOffset;

  // remaining internal signals
  reg [1 : 0] mask__h798;
  wire [63 : 0] addBase__h840,
		pointer__h67,
		result_d_address__h812,
		ret___1_address__h822,
		x__h704,
		x__h950;
  wire [49 : 0] highOffsetBits__h74, mask__h841, signBits__h71, x__h101;
  wire [15 : 0] x__h891;
  wire [13 : 0] newAddrBits__h797,
		repBoundBits__h80,
		result_d_addrBits__h813,
		toBoundsM1_A__h79,
		toBoundsM1_B__h82,
		toBoundsM1__h84,
		toBounds_A__h78,
		toBounds_B__h81,
		toBounds__h83;
  wire [3 : 0] IF_wrap128_modifyOffset_cap_BITS_37_TO_35_9_UL_ETC___d83;
  wire [2 : 0] repBound__h1089;
  wire IF_wrap128_modifyOffset_doInc_THEN_wrap128_mod_ETC___d73,
       IF_wrap128_modifyOffset_offset_BIT_63_THEN_NOT_ETC___d34,
       NOT_wrap128_modifyOffset_offset_SRL_wrap128_mo_ETC___d25,
       wrap128_modifyOffset_cap_BITS_23_TO_21_7_ULT_w_ETC___d71,
       wrap128_modifyOffset_cap_BITS_37_TO_35_9_ULT_w_ETC___d70;

  // value method wrap128_modifyOffset
  assign wrap128_modifyOffset =
	     { highOffsetBits__h74 == 50'd0 &&
	       IF_wrap128_modifyOffset_offset_BIT_63_THEN_NOT_ETC___d34 ||
	       wrap128_modifyOffset_cap[43:38] >= 6'd50,
	       (highOffsetBits__h74 == 50'd0 &&
		IF_wrap128_modifyOffset_offset_BIT_63_THEN_NOT_ETC___d34 ||
		wrap128_modifyOffset_cap[43:38] >= 6'd50) &&
	       wrap128_modifyOffset_cap[160],
	       result_d_address__h812,
	       result_d_addrBits__h813,
	       wrap128_modifyOffset_cap[81:10],
	       repBound__h1089,
	       wrap128_modifyOffset_cap_BITS_37_TO_35_9_ULT_w_ETC___d70,
	       wrap128_modifyOffset_cap_BITS_23_TO_21_7_ULT_w_ETC___d71,
	       IF_wrap128_modifyOffset_doInc_THEN_wrap128_mod_ETC___d73,
	       IF_wrap128_modifyOffset_cap_BITS_37_TO_35_9_UL_ETC___d83 } ;

  // remaining internal signals
  assign IF_wrap128_modifyOffset_cap_BITS_37_TO_35_9_UL_ETC___d83 =
	     { (wrap128_modifyOffset_cap_BITS_37_TO_35_9_ULT_w_ETC___d70 ==
		IF_wrap128_modifyOffset_doInc_THEN_wrap128_mod_ETC___d73) ?
		 2'd0 :
		 ((wrap128_modifyOffset_cap_BITS_37_TO_35_9_ULT_w_ETC___d70 &&
		   !IF_wrap128_modifyOffset_doInc_THEN_wrap128_mod_ETC___d73) ?
		    2'd1 :
		    2'd3),
	       (wrap128_modifyOffset_cap_BITS_23_TO_21_7_ULT_w_ETC___d71 ==
		IF_wrap128_modifyOffset_doInc_THEN_wrap128_mod_ETC___d73) ?
		 2'd0 :
		 ((wrap128_modifyOffset_cap_BITS_23_TO_21_7_ULT_w_ETC___d71 &&
		   !IF_wrap128_modifyOffset_doInc_THEN_wrap128_mod_ETC___d73) ?
		    2'd1 :
		    2'd3) } ;
  assign IF_wrap128_modifyOffset_doInc_THEN_wrap128_mod_ETC___d73 =
	     result_d_addrBits__h813[13:11] < repBound__h1089 ;
  assign IF_wrap128_modifyOffset_offset_BIT_63_THEN_NOT_ETC___d34 =
	     wrap128_modifyOffset_offset[63] ?
	       NOT_wrap128_modifyOffset_offset_SRL_wrap128_mo_ETC___d25 :
	       (wrap128_modifyOffset_doInc ?
		  x__h704[13:0] < toBoundsM1__h84 :
		  x__h704[13:0] <= toBoundsM1__h84) ;
  assign NOT_wrap128_modifyOffset_offset_SRL_wrap128_mo_ETC___d25 =
	     x__h704[13:0] >= toBounds__h83 &&
	     (!wrap128_modifyOffset_doInc ||
	      repBoundBits__h80 != wrap128_modifyOffset_cap[95:82]) ;
  assign addBase__h840 =
	     { {48{x__h891[15]}}, x__h891 } <<
	     wrap128_modifyOffset_cap[43:38] ;
  assign highOffsetBits__h74 = x__h101 & mask__h841 ;
  assign mask__h841 = 50'h3FFFFFFFFFFFF << wrap128_modifyOffset_cap[43:38] ;
  assign newAddrBits__h797 = wrap128_modifyOffset_cap[23:10] + x__h704[13:0] ;
  assign pointer__h67 =
	     wrap128_modifyOffset_cap[159:96] + wrap128_modifyOffset_offset ;
  assign repBoundBits__h80 = { wrap128_modifyOffset_cap[9:7], 11'd0 } ;
  assign repBound__h1089 = wrap128_modifyOffset_cap[23:21] - 3'b001 ;
  assign result_d_addrBits__h813 =
	     wrap128_modifyOffset_doInc ?
	       x__h950[13:0] :
	       { mask__h798, 12'd4095 } & newAddrBits__h797 ;
  assign result_d_address__h812 =
	     wrap128_modifyOffset_doInc ?
	       pointer__h67 :
	       ret___1_address__h822 ;
  assign ret___1_address__h822 =
	     { wrap128_modifyOffset_cap[159:110] & mask__h841, 14'd0 } +
	     addBase__h840 +
	     wrap128_modifyOffset_offset ;
  assign signBits__h71 = {50{wrap128_modifyOffset_offset[63]}} ;
  assign toBoundsM1_A__h79 = { 3'b110, ~wrap128_modifyOffset_cap[20:10] } ;
  assign toBoundsM1_B__h82 =
	     repBoundBits__h80 + ~wrap128_modifyOffset_cap[95:82] ;
  assign toBoundsM1__h84 =
	     wrap128_modifyOffset_doInc ?
	       toBoundsM1_B__h82 :
	       toBoundsM1_A__h79 ;
  assign toBounds_A__h78 =
	     14'd14336 - { 3'b0, wrap128_modifyOffset_cap[20:10] } ;
  assign toBounds_B__h81 =
	     repBoundBits__h80 - wrap128_modifyOffset_cap[95:82] ;
  assign toBounds__h83 =
	     wrap128_modifyOffset_doInc ? toBounds_B__h81 : toBounds_A__h78 ;
  assign wrap128_modifyOffset_cap_BITS_23_TO_21_7_ULT_w_ETC___d71 =
	     wrap128_modifyOffset_cap[23:21] < repBound__h1089 ;
  assign wrap128_modifyOffset_cap_BITS_37_TO_35_9_ULT_w_ETC___d70 =
	     wrap128_modifyOffset_cap[37:35] < repBound__h1089 ;
  assign x__h101 = wrap128_modifyOffset_offset[63:14] ^ signBits__h71 ;
  assign x__h704 =
	     wrap128_modifyOffset_offset >> wrap128_modifyOffset_cap[43:38] ;
  assign x__h891 =
	     { wrap128_modifyOffset_cap[1:0],
	       wrap128_modifyOffset_cap[23:10] } ;
  assign x__h950 = pointer__h67 >> wrap128_modifyOffset_cap[43:38] ;
  always@(wrap128_modifyOffset_cap)
  begin
    case (wrap128_modifyOffset_cap[43:38])
      6'd51: mask__h798 = 2'b01;
      6'd52: mask__h798 = 2'b0;
      default: mask__h798 = 2'b11;
    endcase
  end
endmodule  // module_wrap128_modifyOffset

