//
// Generated by Bluespec Compiler, version 2024.07 (build b4f31db)
//
// On Fri Mar 13 11:37:57 CET 2026
//
//
// Ports:
// Name                         I/O  size props
// wrap128_getBase                O    64
// wrap128_getBase_cap            I   161
//
// Combinational paths from inputs to outputs:
//   wrap128_getBase_cap -> wrap128_getBase
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_wrap128_getBase(wrap128_getBase_cap,
			      wrap128_getBase);
  // value method wrap128_getBase
  input  [160 : 0] wrap128_getBase_cap;
  output [63 : 0] wrap128_getBase;

  // signals for module outputs
  wire [63 : 0] wrap128_getBase;

  // remaining internal signals
  wire [63 : 0] addBase__h57;
  wire [49 : 0] mask__h58;
  wire [15 : 0] x__h156;

  // value method wrap128_getBase
  assign wrap128_getBase =
	     { wrap128_getBase_cap[159:110] & mask__h58, 14'd0 } +
	     addBase__h57 ;

  // remaining internal signals
  assign addBase__h57 =
	     { {48{x__h156[15]}}, x__h156 } << wrap128_getBase_cap[43:38] ;
  assign mask__h58 = 50'h3FFFFFFFFFFFF << wrap128_getBase_cap[43:38] ;
  assign x__h156 = { wrap128_getBase_cap[1:0], wrap128_getBase_cap[23:10] } ;
endmodule  // module_wrap128_getBase

