//
// Generated by Bluespec Compiler, version 2024.07 (build b4f31db)
//
// On Fri Mar 13 11:37:57 CET 2026
//
//
// Ports:
// Name                         I/O  size props
// wrap128_getTop                 O    65
// wrap128_getTop_cap             I   161
//
// Combinational paths from inputs to outputs:
//   wrap128_getTop_cap -> wrap128_getTop
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_wrap128_getTop(wrap128_getTop_cap,
			     wrap128_getTop);
  // value method wrap128_getTop
  input  [160 : 0] wrap128_getTop_cap;
  output [64 : 0] wrap128_getTop;

  // signals for module outputs
  wire [64 : 0] wrap128_getTop;

  // remaining internal signals
  wire [64 : 0] addTop__h57, result__h683, ret__h59;
  wire [50 : 0] mask__h58;
  wire [49 : 0] wrap128_getTop_cap_BITS_159_TO_110_PLUS_SEXT_w_ETC__q2;
  wire [15 : 0] x__h167;
  wire [1 : 0] wrap128_getTop_cap_BITS_1_TO_0__q1;

  // value method wrap128_getTop
  assign wrap128_getTop =
	     (wrap128_getTop_cap[43:38] < 6'd51 &&
	      ret__h59[64:63] -
	      { 1'b0,
		(wrap128_getTop_cap[43:38] == 6'd50) ?
		  wrap128_getTop_cap[23] :
		  wrap128_getTop_cap_BITS_159_TO_110_PLUS_SEXT_w_ETC__q2[49] } >
	      2'd1) ?
	       result__h683 :
	       ret__h59 ;

  // remaining internal signals
  assign addTop__h57 =
	     { {49{x__h167[15]}}, x__h167 } << wrap128_getTop_cap[43:38] ;
  assign mask__h58 = 51'h7FFFFFFFFFFFF << wrap128_getTop_cap[43:38] ;
  assign result__h683 = { ~ret__h59[64], ret__h59[63:0] } ;
  assign ret__h59 =
	     { { 1'b0, wrap128_getTop_cap[159:110] } & mask__h58, 14'd0 } +
	     addTop__h57 ;
  assign wrap128_getTop_cap_BITS_159_TO_110_PLUS_SEXT_w_ETC__q2 =
	     wrap128_getTop_cap[159:110] +
	     ({ {48{wrap128_getTop_cap_BITS_1_TO_0__q1[1]}},
		wrap128_getTop_cap_BITS_1_TO_0__q1 } <<
	      wrap128_getTop_cap[43:38]) ;
  assign wrap128_getTop_cap_BITS_1_TO_0__q1 = wrap128_getTop_cap[1:0] ;
  assign x__h167 = { wrap128_getTop_cap[3:2], wrap128_getTop_cap[37:24] } ;
endmodule  // module_wrap128_getTop

