//
// Generated by Bluespec Compiler, version 2024.07 (build b4f31db)
//
// On Fri Mar 13 11:37:57 CET 2026
//
//
// Ports:
// Name                         I/O  size props
// wrap128_getHardPerms           O    12
// wrap128_getHardPerms_cap       I   161
//
// Combinational paths from inputs to outputs:
//   wrap128_getHardPerms_cap -> wrap128_getHardPerms
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_wrap128_getHardPerms(wrap128_getHardPerms_cap,
				   wrap128_getHardPerms);
  // value method wrap128_getHardPerms
  input  [160 : 0] wrap128_getHardPerms_cap;
  output [11 : 0] wrap128_getHardPerms;

  // signals for module outputs
  wire [11 : 0] wrap128_getHardPerms;

  // value method wrap128_getHardPerms
  assign wrap128_getHardPerms = wrap128_getHardPerms_cap[77:66] ;
endmodule  // module_wrap128_getHardPerms

