//
// Generated by Bluespec Compiler, version 2024.07 (build b4f31db)
//
// On Fri Mar 13 11:37:57 CET 2026
//
//
// Ports:
// Name                         I/O  size props
// wrap128_getOffset              O    64
// wrap128_getOffset_cap          I   161
//
// Combinational paths from inputs to outputs:
//   wrap128_getOffset_cap -> wrap128_getOffset
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_wrap128_getOffset(wrap128_getOffset_cap,
				wrap128_getOffset);
  // value method wrap128_getOffset
  input  [160 : 0] wrap128_getOffset_cap;
  output [63 : 0] wrap128_getOffset;

  // signals for module outputs
  wire [63 : 0] wrap128_getOffset;

  // remaining internal signals
  wire [63 : 0] addrLSB__h61, x__h193, x__h72, x__h74, y__h192;
  wire [15 : 0] base__h59, offset__h60;

  // value method wrap128_getOffset
  assign wrap128_getOffset = x__h72 | addrLSB__h61 ;

  // remaining internal signals
  assign addrLSB__h61 = wrap128_getOffset_cap[159:96] & y__h192 ;
  assign base__h59 =
	     { wrap128_getOffset_cap[1:0], wrap128_getOffset_cap[23:10] } ;
  assign offset__h60 = { 2'b0, wrap128_getOffset_cap[95:82] } - base__h59 ;
  assign x__h193 = 64'hFFFFFFFFFFFFFFFF << wrap128_getOffset_cap[43:38] ;
  assign x__h72 = x__h74 << wrap128_getOffset_cap[43:38] ;
  assign x__h74 = { {48{offset__h60[15]}}, offset__h60 } ;
  assign y__h192 = ~x__h193 ;
endmodule  // module_wrap128_getOffset

