//
// Generated by Bluespec Compiler, version 2024.07 (build b4f31db)
//
// On Fri Mar 13 11:37:57 CET 2026
//
//
// Ports:
// Name                         I/O  size props
// wrap128_getFlags               O     1
// wrap128_getFlags_cap           I   161
//
// Combinational paths from inputs to outputs:
//   wrap128_getFlags_cap -> wrap128_getFlags
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_wrap128_getFlags(wrap128_getFlags_cap,
			       wrap128_getFlags);
  // value method wrap128_getFlags
  input  [160 : 0] wrap128_getFlags_cap;
  output wrap128_getFlags;

  // signals for module outputs
  wire wrap128_getFlags;

  // value method wrap128_getFlags
  assign wrap128_getFlags = wrap128_getFlags_cap[65] ;
endmodule  // module_wrap128_getFlags

