//
// Generated by Bluespec Compiler, version 2024.07 (build b4f31db)
//
// On Fri Mar 13 11:37:58 CET 2026
//
//
// Ports:
// Name                         I/O  size props
// wrap128_nullWithAddr           O   161
// wrap128_nullWithAddr_addr      I    64
//
// Combinational paths from inputs to outputs:
//   wrap128_nullWithAddr_addr -> wrap128_nullWithAddr
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_wrap128_nullWithAddr(wrap128_nullWithAddr_addr,
				   wrap128_nullWithAddr);
  // value method wrap128_nullWithAddr
  input  [63 : 0] wrap128_nullWithAddr_addr;
  output [160 : 0] wrap128_nullWithAddr;

  // signals for module outputs
  wire [160 : 0] wrap128_nullWithAddr;

  // remaining internal signals
  wire [13 : 0] res_addrBits__h102;

  // value method wrap128_nullWithAddr
  assign wrap128_nullWithAddr =
	     { 1'd0,
	       wrap128_nullWithAddr_addr,
	       res_addrBits__h102,
	       82'h000007FFFFD10000003F0 } ;

  // remaining internal signals
  assign res_addrBits__h102 = { 2'd0, wrap128_nullWithAddr_addr[63:52] } ;
endmodule  // module_wrap128_nullWithAddr

