//
// Generated by Bluespec Compiler, version 2024.07 (build b4f31db)
//
// On Fri Mar 13 11:37:57 CET 2026
//
//
// Ports:
// Name                         I/O  size props
// wrap128_setHardPerms           O   161
// wrap128_setHardPerms_cap       I   161
// wrap128_setHardPerms_hardperms  I    12
//
// Combinational paths from inputs to outputs:
//   (wrap128_setHardPerms_cap,
//    wrap128_setHardPerms_hardperms) -> wrap128_setHardPerms
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_wrap128_setHardPerms(wrap128_setHardPerms_cap,
				   wrap128_setHardPerms_hardperms,
				   wrap128_setHardPerms);
  // value method wrap128_setHardPerms
  input  [160 : 0] wrap128_setHardPerms_cap;
  input  [11 : 0] wrap128_setHardPerms_hardperms;
  output [160 : 0] wrap128_setHardPerms;

  // signals for module outputs
  wire [160 : 0] wrap128_setHardPerms;

  // value method wrap128_setHardPerms
  assign wrap128_setHardPerms =
	     { wrap128_setHardPerms_cap[160:78],
	       wrap128_setHardPerms_hardperms,
	       wrap128_setHardPerms_cap[65:0] } ;
endmodule  // module_wrap128_setHardPerms

