//
// Generated by Bluespec Compiler, version 2024.07 (build b4f31db)
//
// On Fri Mar 13 11:37:57 CET 2026
//
//
// Ports:
// Name                         I/O  size props
// wrap128_getLength              O    65
// wrap128_getLength_cap          I   161
//
// Combinational paths from inputs to outputs:
//   wrap128_getLength_cap -> wrap128_getLength
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_wrap128_getLength(wrap128_getLength_cap,
				wrap128_getLength);
  // value method wrap128_getLength
  input  [160 : 0] wrap128_getLength_cap;
  output [64 : 0] wrap128_getLength;

  // signals for module outputs
  wire [64 : 0] wrap128_getLength;

  // remaining internal signals
  wire [64 : 0] length__h59;
  wire [15 : 0] base__h58, top__h57, x__h114;

  // value method wrap128_getLength
  assign wrap128_getLength =
	     (wrap128_getLength_cap[43:38] < 6'd52) ?
	       length__h59 :
	       65'h1FFFFFFFFFFFFFFFF ;

  // remaining internal signals
  assign base__h58 =
	     { wrap128_getLength_cap[1:0], wrap128_getLength_cap[23:10] } ;
  assign length__h59 = { 49'd0, x__h114 } << wrap128_getLength_cap[43:38] ;
  assign top__h57 =
	     { wrap128_getLength_cap[3:2], wrap128_getLength_cap[37:24] } ;
  assign x__h114 = top__h57 - base__h58 ;
endmodule  // module_wrap128_getLength

