//
// Generated by Bluespec Compiler, version 2024.07 (build b4f31db)
//
// On Fri Mar 13 11:37:57 CET 2026
//
//
// Ports:
// Name                         I/O  size props
// wrap128_getPerms               O    31
// wrap128_getPerms_cap           I   161
//
// Combinational paths from inputs to outputs:
//   wrap128_getPerms_cap -> wrap128_getPerms
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_wrap128_getPerms(wrap128_getPerms_cap,
			       wrap128_getPerms);
  // value method wrap128_getPerms
  input  [160 : 0] wrap128_getPerms_cap;
  output [30 : 0] wrap128_getPerms;

  // signals for module outputs
  wire [30 : 0] wrap128_getPerms;

  // value method wrap128_getPerms
  assign wrap128_getPerms =
	     { 12'd0,
	       wrap128_getPerms_cap[81:78],
	       3'h0,
	       wrap128_getPerms_cap[77:66] } ;
endmodule  // module_wrap128_getPerms

