//
// Generated by Bluespec Compiler, version 2024.07 (build b4f31db)
//
// On Fri Mar 13 11:37:57 CET 2026
//
//
// Ports:
// Name                         I/O  size props
// wrap128_setKind                O   161
// wrap128_setKind_cap            I   161
// wrap128_setKind_kind           I    21
//
// Combinational paths from inputs to outputs:
//   (wrap128_setKind_cap, wrap128_setKind_kind) -> wrap128_setKind
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_wrap128_setKind(wrap128_setKind_cap,
			      wrap128_setKind_kind,
			      wrap128_setKind);
  // value method wrap128_setKind
  input  [160 : 0] wrap128_setKind_cap;
  input  [20 : 0] wrap128_setKind_kind;
  output [160 : 0] wrap128_setKind;

  // signals for module outputs
  wire [160 : 0] wrap128_setKind;

  // remaining internal signals
  reg [17 : 0] CASE_wrap128_setKind_kind_BITS_20_TO_18_0_2621_ETC__q1;

  // value method wrap128_setKind
  assign wrap128_setKind =
	     { wrap128_setKind_cap[160:63],
	       CASE_wrap128_setKind_kind_BITS_20_TO_18_0_2621_ETC__q1,
	       wrap128_setKind_cap[44:0] } ;

  // remaining internal signals
  always@(wrap128_setKind_kind)
  begin
    case (wrap128_setKind_kind[20:18])
      3'd0:
	  CASE_wrap128_setKind_kind_BITS_20_TO_18_0_2621_ETC__q1 = 18'd262143;
      3'd1:
	  CASE_wrap128_setKind_kind_BITS_20_TO_18_0_2621_ETC__q1 = 18'd262142;
      3'd2:
	  CASE_wrap128_setKind_kind_BITS_20_TO_18_0_2621_ETC__q1 = 18'd262141;
      3'd3:
	  CASE_wrap128_setKind_kind_BITS_20_TO_18_0_2621_ETC__q1 = 18'd262140;
      default: CASE_wrap128_setKind_kind_BITS_20_TO_18_0_2621_ETC__q1 =
		   wrap128_setKind_kind[17:0];
    endcase
  end
endmodule  // module_wrap128_setKind

