//
// Generated by Bluespec Compiler, version 2024.07 (build b4f31db)
//
// On Fri Mar 13 11:37:57 CET 2026
//
//
// Ports:
// Name                         I/O  size props
// wrap128_setPerms               O   161
// wrap128_setPerms_cap           I   161
// wrap128_setPerms_perms         I    31
//
// Combinational paths from inputs to outputs:
//   (wrap128_setPerms_cap, wrap128_setPerms_perms) -> wrap128_setPerms
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_wrap128_setPerms(wrap128_setPerms_cap,
			       wrap128_setPerms_perms,
			       wrap128_setPerms);
  // value method wrap128_setPerms
  input  [160 : 0] wrap128_setPerms_cap;
  input  [30 : 0] wrap128_setPerms_perms;
  output [160 : 0] wrap128_setPerms;

  // signals for module outputs
  wire [160 : 0] wrap128_setPerms;

  // value method wrap128_setPerms
  assign wrap128_setPerms =
	     { wrap128_setPerms_cap[160:82],
	       wrap128_setPerms_perms[18:15],
	       wrap128_setPerms_perms[11:0],
	       wrap128_setPerms_cap[65:0] } ;
endmodule  // module_wrap128_setPerms

