//
// Generated by Bluespec Compiler, version 2024.07 (build b4f31db)
//
// On Fri Mar 13 11:37:58 CET 2026
//
//
// Ports:
// Name                         I/O  size props
// wrap128_fromMem                O   161
// wrap128_fromMem_mem_cap        I   129
//
// Combinational paths from inputs to outputs:
//   wrap128_fromMem_mem_cap -> wrap128_fromMem
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_wrap128_fromMem(wrap128_fromMem_mem_cap,
			      wrap128_fromMem);
  // value method wrap128_fromMem
  input  [128 : 0] wrap128_fromMem_mem_cap;
  output [160 : 0] wrap128_fromMem;

  // signals for module outputs
  wire [160 : 0] wrap128_fromMem;

  // remaining internal signals
  wire [63 : 0] x__h385;
  wire [33 : 0] IF_INV_wrap128_fromMem_mem_cap_BITS_108_TO_90__ETC___d40;
  wire [18 : 0] INV_wrap128_fromMem_mem_cap_BITS_108_TO_90__q1;
  wire [13 : 0] b_base__h610, res_addrBits__h116, x__h583, x__h603;
  wire [11 : 0] b_top__h609, topBits__h512;
  wire [5 : 0] x__h423;
  wire [4 : 0] IF_INV_wrap128_fromMem_mem_cap_BITS_108_TO_90__ETC___d60;
  wire [2 : 0] repBound__h664,
	       tb__h661,
	       tmp_expBotHalf__h378,
	       tmp_expTopHalf__h376;
  wire [1 : 0] carry_out__h514,
	       impliedTopBits__h516,
	       len_correction__h515,
	       x__h600;
  wire IF_INV_wrap128_fromMem_mem_cap_BITS_108_TO_90__ETC___d47,
       IF_INV_wrap128_fromMem_mem_cap_BITS_108_TO_90__ETC___d48,
       IF_INV_wrap128_fromMem_mem_cap_BITS_108_TO_90__ETC___d50;

  // value method wrap128_fromMem
  assign wrap128_fromMem =
	     { wrap128_fromMem_mem_cap[128],
	       wrap128_fromMem_mem_cap[63:0],
	       res_addrBits__h116,
	       wrap128_fromMem_mem_cap[127:112],
	       wrap128_fromMem_mem_cap[109],
	       wrap128_fromMem_mem_cap[111:110],
	       ~wrap128_fromMem_mem_cap[108:90],
	       IF_INV_wrap128_fromMem_mem_cap_BITS_108_TO_90__ETC___d40,
	       repBound__h664,
	       IF_INV_wrap128_fromMem_mem_cap_BITS_108_TO_90__ETC___d47,
	       IF_INV_wrap128_fromMem_mem_cap_BITS_108_TO_90__ETC___d48,
	       IF_INV_wrap128_fromMem_mem_cap_BITS_108_TO_90__ETC___d60 } ;

  // remaining internal signals
  assign IF_INV_wrap128_fromMem_mem_cap_BITS_108_TO_90__ETC___d40 =
	     { INV_wrap128_fromMem_mem_cap_BITS_108_TO_90__q1[0] ?
		 x__h423 :
		 6'd0,
	       x__h583,
	       x__h603 } ;
  assign IF_INV_wrap128_fromMem_mem_cap_BITS_108_TO_90__ETC___d47 =
	     tb__h661 < repBound__h664 ;
  assign IF_INV_wrap128_fromMem_mem_cap_BITS_108_TO_90__ETC___d48 =
	     x__h603[13:11] < repBound__h664 ;
  assign IF_INV_wrap128_fromMem_mem_cap_BITS_108_TO_90__ETC___d50 =
	     res_addrBits__h116[13:11] < repBound__h664 ;
  assign IF_INV_wrap128_fromMem_mem_cap_BITS_108_TO_90__ETC___d60 =
	     { IF_INV_wrap128_fromMem_mem_cap_BITS_108_TO_90__ETC___d50,
	       (IF_INV_wrap128_fromMem_mem_cap_BITS_108_TO_90__ETC___d47 ==
		IF_INV_wrap128_fromMem_mem_cap_BITS_108_TO_90__ETC___d50) ?
		 2'd0 :
		 ((IF_INV_wrap128_fromMem_mem_cap_BITS_108_TO_90__ETC___d47 &&
		   !IF_INV_wrap128_fromMem_mem_cap_BITS_108_TO_90__ETC___d50) ?
		    2'd1 :
		    2'd3),
	       (IF_INV_wrap128_fromMem_mem_cap_BITS_108_TO_90__ETC___d48 ==
		IF_INV_wrap128_fromMem_mem_cap_BITS_108_TO_90__ETC___d50) ?
		 2'd0 :
		 ((IF_INV_wrap128_fromMem_mem_cap_BITS_108_TO_90__ETC___d48 &&
		   !IF_INV_wrap128_fromMem_mem_cap_BITS_108_TO_90__ETC___d50) ?
		    2'd1 :
		    2'd3) } ;
  assign INV_wrap128_fromMem_mem_cap_BITS_108_TO_90__q1 =
	     ~wrap128_fromMem_mem_cap[108:90] ;
  assign b_base__h610 =
	     { wrap128_fromMem_mem_cap[77:67],
	       ~wrap128_fromMem_mem_cap[66],
	       wrap128_fromMem_mem_cap[65:64] } ;
  assign b_top__h609 =
	     { wrap128_fromMem_mem_cap[89:81],
	       ~wrap128_fromMem_mem_cap[80:79],
	       wrap128_fromMem_mem_cap[78] } ;
  assign carry_out__h514 = (topBits__h512 < x__h603[11:0]) ? 2'b01 : 2'b0 ;
  assign impliedTopBits__h516 = x__h600 + len_correction__h515 ;
  assign len_correction__h515 =
	     INV_wrap128_fromMem_mem_cap_BITS_108_TO_90__q1[0] ?
	       2'b01 :
	       2'b0 ;
  assign repBound__h664 = x__h603[13:11] - 3'b001 ;
  assign res_addrBits__h116 =
	     INV_wrap128_fromMem_mem_cap_BITS_108_TO_90__q1[0] ?
	       x__h385[13:0] :
	       wrap128_fromMem_mem_cap[13:0] ;
  assign tb__h661 = { impliedTopBits__h516, topBits__h512[11] } ;
  assign tmp_expBotHalf__h378 =
	     { ~wrap128_fromMem_mem_cap[66],
	       wrap128_fromMem_mem_cap[65:64] } ;
  assign tmp_expTopHalf__h376 =
	     { ~wrap128_fromMem_mem_cap[80:79],
	       wrap128_fromMem_mem_cap[78] } ;
  assign topBits__h512 =
	     INV_wrap128_fromMem_mem_cap_BITS_108_TO_90__q1[0] ?
	       { wrap128_fromMem_mem_cap[89:81], 3'd0 } :
	       b_top__h609 ;
  assign x__h385 = wrap128_fromMem_mem_cap[63:0] >> x__h423 ;
  assign x__h423 = { tmp_expTopHalf__h376, tmp_expBotHalf__h378 } ;
  assign x__h583 = { impliedTopBits__h516, topBits__h512 } ;
  assign x__h600 = x__h603[13:12] + carry_out__h514 ;
  assign x__h603 =
	     INV_wrap128_fromMem_mem_cap_BITS_108_TO_90__q1[0] ?
	       { wrap128_fromMem_mem_cap[77:67], 3'd0 } :
	       b_base__h610 ;
endmodule  // module_wrap128_fromMem

