//
// Generated by Bluespec Compiler, version 2024.07 (build b4f31db)
//
// On Fri Mar 13 11:37:57 CET 2026
//
//
// Ports:
// Name                         I/O  size props
// wrap128_setAddr                O   162
// wrap128_setAddr_cap            I   161
// wrap128_setAddr_addr           I    64
//
// Combinational paths from inputs to outputs:
//   (wrap128_setAddr_cap, wrap128_setAddr_addr) -> wrap128_setAddr
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_wrap128_setAddr(wrap128_setAddr_cap,
			      wrap128_setAddr_addr,
			      wrap128_setAddr);
  // value method wrap128_setAddr
  input  [160 : 0] wrap128_setAddr_cap;
  input  [63 : 0] wrap128_setAddr_addr;
  output [161 : 0] wrap128_setAddr;

  // signals for module outputs
  wire [161 : 0] wrap128_setAddr;

  // remaining internal signals
  wire [63 : 0] x__h94;
  wire [49 : 0] deltaAddrHi__h69, deltaAddrUpper__h71, mask__h70;
  wire [3 : 0] IF_wrap128_setAddr_cap_BITS_37_TO_35_7_ULT_wra_ETC___d40;
  wire [2 : 0] repBound__h415;
  wire [1 : 0] x__h77;
  wire SEXT__0b0_CONCAT_wrap128_setAddr_addr_SRL_wrap_ETC___d18,
       wrap128_setAddr_addr_SRL_wrap128_setAddr_cap_B_ETC___d30,
       wrap128_setAddr_cap_BITS_23_TO_21_5_ULT_wrap12_ETC___d29,
       wrap128_setAddr_cap_BITS_37_TO_35_7_ULT_wrap12_ETC___d28;

  // value method wrap128_setAddr
  assign wrap128_setAddr =
	     { SEXT__0b0_CONCAT_wrap128_setAddr_addr_SRL_wrap_ETC___d18,
	       SEXT__0b0_CONCAT_wrap128_setAddr_addr_SRL_wrap_ETC___d18 &&
	       wrap128_setAddr_cap[160],
	       wrap128_setAddr_addr,
	       x__h94[13:0],
	       wrap128_setAddr_cap[81:10],
	       repBound__h415,
	       wrap128_setAddr_cap_BITS_37_TO_35_7_ULT_wrap12_ETC___d28,
	       wrap128_setAddr_cap_BITS_23_TO_21_5_ULT_wrap12_ETC___d29,
	       wrap128_setAddr_addr_SRL_wrap128_setAddr_cap_B_ETC___d30,
	       IF_wrap128_setAddr_cap_BITS_37_TO_35_7_ULT_wra_ETC___d40 } ;

  // remaining internal signals
  assign IF_wrap128_setAddr_cap_BITS_37_TO_35_7_ULT_wra_ETC___d40 =
	     { (wrap128_setAddr_cap_BITS_37_TO_35_7_ULT_wrap12_ETC___d28 ==
		wrap128_setAddr_addr_SRL_wrap128_setAddr_cap_B_ETC___d30) ?
		 2'd0 :
		 ((wrap128_setAddr_cap_BITS_37_TO_35_7_ULT_wrap12_ETC___d28 &&
		   !wrap128_setAddr_addr_SRL_wrap128_setAddr_cap_B_ETC___d30) ?
		    2'd1 :
		    2'd3),
	       (wrap128_setAddr_cap_BITS_23_TO_21_5_ULT_wrap12_ETC___d29 ==
		wrap128_setAddr_addr_SRL_wrap128_setAddr_cap_B_ETC___d30) ?
		 2'd0 :
		 ((wrap128_setAddr_cap_BITS_23_TO_21_5_ULT_wrap12_ETC___d29 &&
		   !wrap128_setAddr_addr_SRL_wrap128_setAddr_cap_B_ETC___d30) ?
		    2'd1 :
		    2'd3) } ;
  assign SEXT__0b0_CONCAT_wrap128_setAddr_addr_SRL_wrap_ETC___d18 =
	     deltaAddrHi__h69 == deltaAddrUpper__h71 ;
  assign deltaAddrHi__h69 =
	     { {48{x__h77[1]}}, x__h77 } << wrap128_setAddr_cap[43:38] ;
  assign deltaAddrUpper__h71 =
	     (wrap128_setAddr_addr[63:14] & mask__h70) -
	     (wrap128_setAddr_cap[159:110] & mask__h70) ;
  assign mask__h70 = 50'h3FFFFFFFFFFFF << wrap128_setAddr_cap[43:38] ;
  assign repBound__h415 = wrap128_setAddr_cap[23:21] - 3'b001 ;
  assign wrap128_setAddr_addr_SRL_wrap128_setAddr_cap_B_ETC___d30 =
	     x__h94[13:11] < repBound__h415 ;
  assign wrap128_setAddr_cap_BITS_23_TO_21_5_ULT_wrap12_ETC___d29 =
	     wrap128_setAddr_cap[23:21] < repBound__h415 ;
  assign wrap128_setAddr_cap_BITS_37_TO_35_7_ULT_wrap12_ETC___d28 =
	     wrap128_setAddr_cap[37:35] < repBound__h415 ;
  assign x__h77 =
	     { 1'b0, x__h94[13:11] < wrap128_setAddr_cap[9:7] } -
	     { 1'b0, wrap128_setAddr_cap[4] } ;
  assign x__h94 = wrap128_setAddr_addr >> wrap128_setAddr_cap[43:38] ;
endmodule  // module_wrap128_setAddr

