//
// Generated by Bluespec Compiler, version 2024.07 (build b4f31db)
//
// On Fri Mar 13 11:37:57 CET 2026
//
//
// Ports:
// Name                         I/O  size props
// wrap128_getAddr                O    64
// wrap128_getAddr_cap            I   161
//
// Combinational paths from inputs to outputs:
//   wrap128_getAddr_cap -> wrap128_getAddr
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_wrap128_getAddr(wrap128_getAddr_cap,
			      wrap128_getAddr);
  // value method wrap128_getAddr
  input  [160 : 0] wrap128_getAddr_cap;
  output [63 : 0] wrap128_getAddr;

  // signals for module outputs
  wire [63 : 0] wrap128_getAddr;

  // value method wrap128_getAddr
  assign wrap128_getAddr = wrap128_getAddr_cap[159:96] ;
endmodule  // module_wrap128_getAddr

